const mongoose = require('mongoose');
const { ClassRoom, User, Progress, ActivityResult, LearningSession, Assignment, TeacherNote, CurriculumUnit, CurriculumBook, Lesson, Activity } = require('../models');

const validId = id => mongoose.isValidObjectId(id);
const invalid = (res, message) => res.status(400).json({ success: false, message });
const classFor = (req, id) => ClassRoom.findOne(req.user.role === 'ADMIN' ? { _id: id } : { _id: id, teacher: req.user._id });
const studentsFor = async req => ClassRoom.find({ teacher: req.user._id }).distinct('students');
const getStudent = async (req, id) => validId(id) ? User.findOne({ role: 'CHILD', $and: [{ _id: id }, { _id: { $in: await studentsFor(req) } }] }).select('-password -pin') : null;
const statsFor = ids => ids.length ? ActivityResult.aggregate([{ $match: { child: { $in: ids } } }, { $group: { _id: '$child', averageScore: { $avg: '$score' }, stars: { $sum: '$stars' }, attempts: { $sum: '$attempts' }, learningTime: { $sum: '$duration' }, lastActivity: { $max: '$createdAt' } } }]) : [];
const ownClassOr403 = async (req, res, id) => { if (!validId(id)) { invalid(res, 'Invalid classroom id.'); return null; } const item = await classFor(req, id); if (!item) res.status(403).json({ success: false, message: 'You do not have access to this classroom.' }); return item; };

exports.getDashboard = async (req, res, next) => { try {
  const classes = await ClassRoom.find({ teacher: req.user._id }).select('students'); const ids = classes.flatMap(c => c.students);
  const [assignmentData, resultStats, recentSessions] = await Promise.all([Assignment.find({ teacher: req.user._id }).sort({ createdAt: -1 }).limit(6).populate('classRoom', 'name').populate('lesson', 'title').populate('activity', 'title activityType'), statsFor(ids), LearningSession.find({ child: { $in: ids } }).sort({ lastActivityAt: -1 }).limit(8).populate('child', 'name avatar avatarUrl').populate('lesson', 'title')]);
  const avg = resultStats.length ? Math.round(resultStats.reduce((n, x) => n + x.averageScore, 0) / resultStats.length) : 0;
  res.json({ success: true, data: { metrics: { classes: classes.length, students: ids.length, activeAssignments: assignmentData.filter(x => ['ASSIGNED', 'IN_PROGRESS'].includes(x.status)).length, completedAssignments: assignmentData.filter(x => x.status === 'COMPLETED').length, needingAttention: ids.filter(id => { const x = resultStats.find(y => String(y._id) === String(id)); return !x || x.averageScore < 60; }).length, averageScore: avg, stars: resultStats.reduce((n, x) => n + x.stars, 0) }, recentAssignments: assignmentData, recentSessions } });
} catch (e) { next(e); } };

exports.getTeacherClasses = async (req, res, next) => { try {
  const q = { teacher: req.user._id }; if (req.query.status) q.status = req.query.status; if (req.query.ageGroupCode) q.ageGroupCode = req.query.ageGroupCode; if (req.query.search) q.name = { $regex: req.query.search, $options: 'i' };
  const data = await ClassRoom.find(q).populate('teacher', 'name avatar avatarUrl').populate('ageGroup', 'name code').populate('students', 'name avatar avatarUrl ageGroupCode dob lastLogin').sort({ updatedAt: -1 }); res.json({ success: true, count: data.length, data });
} catch (e) { next(e); } };

exports.getClassDetail = async (req, res, next) => { try {
  const classRoom = await ownClassOr403(req, res, req.params.id); if (!classRoom) return;
  await classRoom.populate('teacher', 'name avatar avatarUrl'); await classRoom.populate('ageGroup', 'name code'); await classRoom.populate('students', 'name avatar avatarUrl ageGroupCode dob lastLogin createdAt');
  const [resultStats, assignments] = await Promise.all([statsFor(classRoom.students.map(x => x._id)), Assignment.find({ classRoom: classRoom._id, teacher: req.user._id }).populate('lesson', 'title').populate('activity', 'title activityType').sort({ createdAt: -1 })]); const map = new Map(resultStats.map(x => [String(x._id), x]));
  res.json({ success: true, data: { ...classRoom.toObject(), students: classRoom.students.map(x => ({ ...x.toObject(), stats: map.get(String(x._id)) || { averageScore: 0, stars: 0, attempts: 0, learningTime: 0 } })), assignments } });
} catch (e) { next(e); } };

exports.updateClass = async (req, res, next) => { try {
  if (!validId(req.params.id)) return invalid(res, 'Invalid classroom id.'); const values = {}; ['name', 'description', 'academicYear', 'status'].forEach(k => { if (req.body[k] !== undefined) values[k] = req.body[k]; }); if (req.body.ageGroupCode) values.ageGroupCode = req.body.ageGroupCode;
  if (values.name !== undefined && !String(values.name).trim()) return invalid(res, 'Class name is required.'); const data = await ClassRoom.findOneAndUpdate({ _id: req.params.id, teacher: req.user._id }, values, { new: true, runValidators: true }); if (!data) return res.status(403).json({ success: false, message: 'You do not have access to this classroom.' }); res.json({ success: true, data });
} catch (e) { next(e); } };

exports.getEligibleStudents = async (req, res, next) => { try {
  const room = await ownClassOr403(req, res, req.params.id); if (!room) return; const q = { role: 'CHILD', status: 'ACTIVE', $or: [{ assignedClass: null }, { assignedClass: { $exists: false } }] }; if (req.query.ageGroupCode || room.ageGroupCode) q.ageGroupCode = req.query.ageGroupCode || room.ageGroupCode; if (req.query.search) q.$and = [{ $or: [{ name: { $regex: req.query.search, $options: 'i' } }, { username: { $regex: req.query.search, $options: 'i' } }] }]; const data = await User.find(q).select('name username avatar avatarUrl ageGroupCode dob createdAt').sort({ name: 1 }); res.json({ success: true, data });
} catch (e) { next(e); } };

exports.addStudents = async (req, res, next) => { try {
  const ids = req.body.studentIds; if (!Array.isArray(ids) || !ids.length || ids.some(id => !validId(id))) return invalid(res, 'Provide one or more valid children.'); const room = await ownClassOr403(req, res, req.params.id); if (!room) return;
  const students = await User.find({ _id: { $in: ids }, role: 'CHILD', status: 'ACTIVE', $or: [{ assignedClass: null }, { assignedClass: { $exists: false } }] }); if (students.length !== ids.length) return invalid(res, 'One or more children are unavailable or already assigned.'); if (room.ageGroupCode && students.some(s => s.ageGroupCode && s.ageGroupCode !== room.ageGroupCode)) return invalid(res, 'Selected children do not match the class age group.');
  await Promise.all([User.updateMany({ _id: { $in: ids } }, { $set: { assignedClass: room._id } }), ClassRoom.updateOne({ _id: room._id }, { $addToSet: { students: { $each: ids } } })]); res.json({ success: true, message: 'Children added to the class.' });
} catch (e) { next(e); } };

exports.removeStudent = async (req, res, next) => { try {
  const room = await ownClassOr403(req, res, req.params.id); if (!room) return; if (!validId(req.params.studentId) || !room.students.some(x => String(x) === req.params.studentId)) return res.status(403).json({ success: false, message: 'This child is not in your class.' }); await Promise.all([ClassRoom.updateOne({ _id: room._id }, { $pull: { students: req.params.studentId } }), User.updateOne({ _id: req.params.studentId, assignedClass: room._id }, { $unset: { assignedClass: 1 } })]); res.json({ success: true, message: 'Child removed from this class. Learning history is preserved.' });
} catch (e) { next(e); } };

exports.getStudents = async (req, res, next) => { try {
  const ids = await studentsFor(req); const q = { _id: { $in: ids }, role: 'CHILD' }; if (req.query.classRoomId) { if (!(await classFor(req, req.query.classRoomId))) return res.status(403).json({ success: false, message: 'You do not have access to this classroom.' }); q.assignedClass = req.query.classRoomId; } if (req.query.ageGroupCode) q.ageGroupCode = req.query.ageGroupCode; if (req.query.search) q.$or = [{ name: { $regex: req.query.search, $options: 'i' } }, { username: { $regex: req.query.search, $options: 'i' } }]; const data = await User.find(q).select('-password -pin').populate('assignedClass', 'name').sort({ name: 1 }); const statMap = new Map((await statsFor(data.map(x => x._id))).map(x => [String(x._id), x])); res.json({ success: true, data: data.map(x => ({ ...x.toObject(), stats: statMap.get(String(x._id)) || {} })) });
} catch (e) { next(e); } };

exports.getStudentOverview = async (req, res, next) => { try {
  const student = await getStudent(req, req.params.studentId); if (!student) return res.status(403).json({ success: false, message: 'You do not have access to this child.' }); const [progressList, recentActivities, sessions, notes, assignments] = await Promise.all([Progress.find({ child: student._id }).populate('lesson', 'title ageGroupCode').populate('topic', 'englishName vietnameseName').sort({ lastActivityAt: -1 }), ActivityResult.find({ child: student._id }).populate('activity', 'title activityType').populate('lesson', 'title').sort({ createdAt: -1 }).limit(20), LearningSession.find({ child: student._id }).populate('lesson', 'title').sort({ lastActivityAt: -1 }).limit(15), TeacherNote.find({ student: student._id, teacher: req.user._id }).populate('teacher', 'name').populate('lesson', 'title').sort({ createdAt: -1 }), Assignment.find({ teacher: req.user._id, $or: [{ student: student._id }, { classRoom: student.assignedClass }] }).populate('lesson', 'title').populate('activity', 'title activityType').sort({ createdAt: -1 })]); const total = recentActivities.reduce((a, r) => ({ stars: a.stars + r.stars, score: a.score + r.score, attempts: a.attempts + r.attempts, seconds: a.seconds + r.duration }), { stars: 0, score: 0, attempts: 0, seconds: 0 }); res.json({ success: true, data: { student, stats: { totalStars: total.stars, completedLessons: progressList.filter(x => x.completed).length, totalActivitiesPlayed: recentActivities.length, averageScore: recentActivities.length ? Math.round(total.score / recentActivities.length) : 0, attempts: total.attempts, learningTime: total.seconds }, progressList, recentActivities, sessions, notes, assignments } });
} catch (e) { next(e); } };

exports.getStudentHistory = async (req, res, next) => { try { const student = await getStudent(req, req.params.studentId); if (!student) return res.status(403).json({ success: false, message: 'You do not have access to this child.' }); const q = { child: student._id }; if (req.query.completed) q.completed = req.query.completed === 'true'; const data = await ActivityResult.find(q).populate('activity', 'title activityType').populate('lesson', 'title').sort({ createdAt: -1 }); res.json({ success: true, data }); } catch (e) { next(e); } };

exports.getContent = async (req, res, next) => { try {
  const uq = { status: 'ACTIVE' }; if (req.query.ageGroupCode) uq.ageGroupCode = req.query.ageGroupCode; if (req.query.bookNumber) uq.bookNumber = Number(req.query.bookNumber); const units = await CurriculumUnit.find(uq).populate('book', 'title bookNumber ageGroupCode').sort({ bookNumber: 1, unitNumber: 1 }).lean(); const activeUnits = req.query.unitId ? units.filter(x => String(x._id) === req.query.unitId) : units; const lq = { status: 'ACTIVE', curriculumUnits: { $in: activeUnits.map(x => x._id) } }; if (req.query.lessonId) lq._id = req.query.lessonId; if (req.query.difficulty) lq.difficulty = Number(req.query.difficulty); const lessons = await Lesson.find(lq).populate('topic', 'englishName vietnameseName').populate('vocabularyItems', 'english vietnamese imageUrl audioUrl').populate('languageContents').sort({ displayOrder: 1 }).lean(); const aq = { status: 'ACTIVE', lesson: { $in: lessons.map(x => x._id) } }; if (req.query.activityType) aq.activityType = req.query.activityType; const activities = await Activity.find(aq).select('title vietnameseTitle lesson activityType difficulty questionCount pointsPerQuestion instructions starConfig ageGroupCode').lean(); res.json({ success: true, data: { books: await CurriculumBook.find({ active: true }).sort({ bookNumber: 1 }), units: activeUnits, lessons, activities } });
} catch (e) { next(e); } };
exports.getLesson = async (req, res, next) => { try { if (!validId(req.params.id)) return invalid(res, 'Invalid lesson id.'); const lesson = await Lesson.findOne({ _id: req.params.id, status: 'ACTIVE' }).populate('topic').populate('vocabularyItems').populate('languageContents').populate('curriculumUnits'); if (!lesson) return res.status(404).json({ success: false, message: 'Lesson not found.' }); const activities = await Activity.find({ lesson: lesson._id, status: 'ACTIVE' }); res.json({ success: true, data: { ...lesson.toObject(), activities } }); } catch (e) { next(e); } };
exports.getActivity = async (req, res, next) => { try { if (!validId(req.params.id)) return invalid(res, 'Invalid activity id.'); const data = await Activity.findOne({ _id: req.params.id, status: 'ACTIVE' }).populate({ path: 'lesson', populate: ['topic', 'vocabularyItems'] }); if (!data) return res.status(404).json({ success: false, message: 'Activity not found.' }); res.json({ success: true, data }); } catch (e) { next(e); } };

exports.createAssignment = async (req, res, next) => { try {
  const { classRoomId, assignedToType = 'CLASS', studentId, lessonId, activityId, dueDate, startDate, instructions } = req.body; if (![classRoomId, lessonId].every(validId) || !['CLASS', 'STUDENT'].includes(assignedToType)) return invalid(res, 'Classroom, lesson and target are required.'); const room = await classFor(req, classRoomId); if (!room) return res.status(403).json({ success: false, message: 'You do not have access to this classroom.' }); if (!(await Lesson.exists({ _id: lessonId, status: 'ACTIVE' }))) return invalid(res, 'Selected lesson is unavailable.'); if (activityId && !(await Activity.exists({ _id: activityId, lesson: lessonId, status: 'ACTIVE' }))) return invalid(res, 'Selected activity is unavailable for this lesson.'); if (assignedToType === 'STUDENT' && (!validId(studentId) || !room.students.some(x => String(x) === studentId))) return invalid(res, 'Selected child is not in this classroom.'); const item = await Assignment.create({ teacher: req.user._id, classRoom: room._id, assignedToType, student: assignedToType === 'STUDENT' ? studentId : null, lesson: lessonId, activity: activityId || null, dueDate: dueDate || null, startDate: startDate || null, instructions: String(instructions || '').trim() }); res.status(201).json({ success: true, data: item });
} catch (e) { next(e); } };
exports.getAssignments = async (req, res, next) => { try { const q = { teacher: req.user._id }; if (req.query.classRoomId) q.classRoom = req.query.classRoomId; if (req.query.status) q.status = req.query.status; const data = await Assignment.find(q).populate('classRoom', 'name students').populate('student', 'name avatar avatarUrl').populate('lesson', 'title').populate('activity', 'title activityType').sort({ createdAt: -1 }); res.json({ success: true, count: data.length, data }); } catch (e) { next(e); } };
exports.getAssignment = async (req, res, next) => { try { const assignment = await Assignment.findOne({ _id: req.params.id, teacher: req.user._id }).populate('classRoom', 'name students').populate('student', 'name avatar').populate('lesson', 'title').populate('activity', 'title activityType'); if (!assignment) return res.status(403).json({ success: false, message: 'You do not have access to this assignment.' }); const ids = assignment.assignedToType === 'STUDENT' ? [assignment.student._id] : assignment.classRoom.students; const results = await ActivityResult.find({ child: { $in: ids }, ...(assignment.activity ? { activity: assignment.activity._id } : { lesson: assignment.lesson._id }) }).populate('child', 'name avatar').sort({ createdAt: -1 }); res.json({ success: true, data: { assignment, results } }); } catch (e) { next(e); } };
exports.updateAssignment = async (req, res, next) => { try { const values = {}; ['dueDate', 'startDate', 'instructions'].forEach(k => { if (req.body[k] !== undefined) values[k] = req.body[k] || null; }); const data = await Assignment.findOneAndUpdate({ _id: req.params.id, teacher: req.user._id, status: { $nin: ['COMPLETED', 'CANCELLED'] } }, values, { new: true, runValidators: true }); if (!data) return res.status(403).json({ success: false, message: 'This assignment cannot be edited.' }); res.json({ success: true, data }); } catch (e) { next(e); } };
exports.updateAssignmentStatus = async (req, res, next) => { try { if (!['ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'].includes(req.body.status)) return invalid(res, 'Invalid assignment status.'); const data = await Assignment.findOneAndUpdate({ _id: req.params.id, teacher: req.user._id }, { status: req.body.status }, { new: true }); if (!data) return res.status(403).json({ success: false, message: 'You do not have access to this assignment.' }); res.json({ success: true, data }); } catch (e) { next(e); } };

exports.createTeacherNote = async (req, res, next) => { try { const { studentId, lessonId, noteType = 'GENERAL', content } = req.body; if (!content || !String(content).trim() || !(await getStudent(req, studentId))) return invalid(res, 'A permitted child and note content are required.'); const data = await TeacherNote.create({ teacher: req.user._id, student: studentId, lesson: validId(lessonId) ? lessonId : null, noteType, content: String(content).trim() }); res.status(201).json({ success: true, data }); } catch (e) { next(e); } };
exports.getStudentNotes = async (req, res, next) => { try { if (!(await getStudent(req, req.params.studentId))) return res.status(403).json({ success: false, message: 'You do not have access to this child.' }); const data = await TeacherNote.find({ student: req.params.studentId, teacher: req.user._id }).populate('teacher', 'name').populate('lesson', 'title').sort({ createdAt: -1 }); res.json({ success: true, data }); } catch (e) { next(e); } };
exports.updateNote = async (req, res, next) => { try { const data = await TeacherNote.findOneAndUpdate({ _id: req.params.id, teacher: req.user._id }, { content: req.body.content, noteType: req.body.noteType }, { new: true, runValidators: true }); if (!data) return res.status(403).json({ success: false, message: 'You can only edit your own note.' }); res.json({ success: true, data }); } catch (e) { next(e); } };
exports.deleteNote = async (req, res, next) => { try { const data = await TeacherNote.findOneAndDelete({ _id: req.params.id, teacher: req.user._id }); if (!data) return res.status(403).json({ success: false, message: 'You can only delete your own note.' }); res.json({ success: true }); } catch (e) { next(e); } };
exports.getCurriculumOptions = exports.getContent;
