/**
 * Official Curriculum Data: 3 Books & 27 Units
 * Source Type: OFFICIAL_CURRICULUM
 */

const AGE_GROUPS_DATA = [
  {
    code: '3-4',
    name: 'Age 3–4 (Book 1)',
    vietnameseName: 'Lớp Mầm (3–4 tuổi)',
    description: 'Single words, large recognition cards, audio-first learning, 2-3 choices',
    targetAgeMin: 3,
    targetAgeMax: 4,
    maxChoicesPerQuestion: 3,
    defaultQuestionCount: 4
  },
  {
    code: '4-5',
    name: 'Age 4–5 (Book 2)',
    vietnameseName: 'Lớp Chồi (4–5 tuổi)',
    description: 'Short phrases, simple matching, everyday descriptions, 3-4 choices',
    targetAgeMin: 4,
    targetAgeMax: 5,
    maxChoicesPerQuestion: 4,
    defaultQuestionCount: 5
  },
  {
    code: '5-6',
    name: 'Age 5–6 (Book 3)',
    vietnameseName: 'Lớp Lá (5–6 tuổi)',
    description: 'Conversational sentences, questions & answers, opinions, reasoning',
    targetAgeMin: 5,
    targetAgeMax: 6,
    maxChoicesPerQuestion: 4,
    defaultQuestionCount: 6
  }
];

const BOOKS_DATA = [
  {
    bookNumber: 1,
    title: 'Book 1',
    ageGroupCode: '3-4',
    description: 'Foundational English curriculum for learners aged 3–4 (9 Units)',
    totalUnits: 9
  },
  {
    bookNumber: 2,
    title: 'Book 2',
    ageGroupCode: '4-5',
    description: 'Expanding English communication curriculum for learners aged 4–5 (9 Units)',
    totalUnits: 9
  },
  {
    bookNumber: 3,
    title: 'Book 3',
    ageGroupCode: '5-6',
    description: 'Advanced conversational & literacy English curriculum for learners aged 5–6 (9 Units)',
    totalUnits: 9
  }
];

const UNITS_DATA = [
  // ===================== BOOK 1 — AGE 3–4 =====================
  {
    key: 'B1_U1',
    bookNumber: 1,
    unitNumber: 1,
    ageGroupCode: '3-4',
    bigQuestion: 'What can we see at school?',
    storyTitle: 'Welcome to School!',
    values: 'Sharing, being friendly, and taking turns at school',
    concept: 'School environment, objects, and people',
    oracy: 'Greeting teacher and naming common school objects',
    crossCurricular: 'Social Studies & Arts',
    numeracy: 'Number 1',
    project: 'Draw and color my favorite school object',
    vocabularyReferences: ['teacher', 'boy', 'girl', 'school', 'sun', 'tree', 'book', 'crayon', 'chair', 'table', 'Leo', 'Tickles', 'Dad', 'Mom', 'Mia'],
    languagePatterns: ['What can you see?', 'I can see a boy.', 'Is it a book?', 'Yes, it is.', 'No, it isn\'t.', 'What is it?', 'It\'s a book.', 'What\'s your name?', 'My name is...', 'What\'s his/her name?', 'His/Her name is...']
  },
  {
    key: 'B1_U2',
    bookNumber: 1,
    unitNumber: 2,
    ageGroupCode: '3-4',
    bigQuestion: 'What do we look like?',
    storyTitle: 'My Wonderful Face',
    values: 'Self-acceptance and recognizing feelings in others',
    concept: 'Facial features and core emotional states',
    oracy: 'Pointing to facial parts and expressing feelings with facial cues',
    crossCurricular: 'Science & Health',
    numeracy: 'Number 2',
    project: 'Make a paper plate happy/sad face mask',
    vocabularyReferences: ['face', 'hair', 'eyes', 'nose', 'forehead', 'mouth', 'ears', 'cheeks', 'happy', 'sad', 'angry'],
    languagePatterns: ['This is my nose.', 'These are my eyes.', 'How do you feel?', 'Are you sad?', 'Are you happy?', 'Are you angry?', 'Yes, I am.', 'No, I\'m not.', 'Yes, s/he is.', 'No, s/he isn\'t.']
  },
  {
    key: 'B1_U3',
    bookNumber: 1,
    unitNumber: 3,
    ageGroupCode: '3-4',
    bigQuestion: 'What can our bodies do?',
    storyTitle: 'Move and Groove!',
    values: 'Physical wellness and joy of movement',
    concept: 'Body parts and active motor verbs',
    oracy: 'Chanting action rhymes while performing actions',
    crossCurricular: 'Physical Education & Biology',
    numeracy: 'Number 3',
    project: 'Action Simon Says game and body tracing',
    vocabularyReferences: ['arms', 'hands', 'legs', 'feet', 'fingers', 'head', 'elbow', 'knee', 'run', 'dance', 'crawl', 'kick'],
    languagePatterns: ['I have a head.', 'I have two knees.', 'S/he has a head.', 'S/he has two feet.', 'Can she dance?', 'Yes, s/he can.', 'No, s/he can\'t.', 'S/he can crawl.', 'Can you run?', 'Yes, I can.', 'No, I can\'t.']
  },
  {
    key: 'B1_U4',
    bookNumber: 1,
    unitNumber: 4,
    ageGroupCode: '3-4',
    bigQuestion: 'What is a family?',
    storyTitle: 'We Love Our Family',
    values: 'Family love, respect for elders, and caring for babies',
    concept: 'Family tree, kinship, and basic physical descriptors',
    oracy: 'Introducing family members with warmth and pride',
    crossCurricular: 'Social Studies & Moral Education',
    numeracy: 'Number 4',
    project: 'Family photo album collage',
    vocabularyReferences: ['father', 'mother', 'sister', 'brother', 'grandfather', 'grandmother', 'baby', 'young', 'old', 'short', 'tall'],
    languagePatterns: ['What is a family?', 'Is this a family?', 'Is he the father?', 'Is she the grandmother?', 'Yes, s/he is.', 'No, s/he isn\'t.', 'What does s/he look like?', 'S/he\'s tall.', 'Is the sister old?', 'Yes.', 'No.', 'My mother is tall.', 'My brother is young.']
  },
  {
    key: 'B1_U5',
    bookNumber: 1,
    unitNumber: 5,
    ageGroupCode: '3-4',
    bigQuestion: 'What is a pet?',
    storyTitle: 'Our Lovely Pets',
    values: 'Kindness and caring for domestic animals',
    concept: 'Pets, animal traits, and animal movements',
    oracy: 'Imitating animal sounds and naming pets clearly',
    crossCurricular: 'Natural Science',
    numeracy: 'Number 5',
    project: 'Pet animal puppet show',
    vocabularyReferences: ['dog', 'bird', 'rabbit', 'fish', 'turtle', 'cat', 'hamster', 'lizard', 'walk', 'jump', 'swim', 'fly'],
    languagePatterns: ['How many birds can you see?', 'I can see two birds.', 'Can cats walk?', 'Yes, they can.', 'No, they can\'t.', 'Cats can walk.', 'Cats can\'t fly.']
  },
  {
    key: 'B1_U6',
    bookNumber: 1,
    unitNumber: 6,
    ageGroupCode: '3-4',
    bigQuestion: 'Can healthy foods be delicious?',
    storyTitle: 'The Yummy Fruit Basket',
    values: 'Healthy eating habits and trying colorful foods',
    concept: 'Fruits, vegetables, colors, and preferences',
    oracy: 'Expressing food likes with enthusiasm',
    crossCurricular: 'Health & Nutrition',
    numeracy: 'Number 6',
    project: 'Create a healthy colorful salad chart',
    vocabularyReferences: ['apple', 'pear', 'tomato', 'carrot', 'bananas', 'grapes', 'cucumbers', 'lettuce', 'pineapple', 'orange', 'potato', 'peas'],
    languagePatterns: ['Which foods do you like?', 'I like bananas.', 'What does s/he have?', 'S/he has an apple.', 'What do you have?', 'I have an/a...']
  },
  {
    key: 'B1_U7',
    bookNumber: 1,
    unitNumber: 7,
    ageGroupCode: '3-4',
    bigQuestion: 'What is a toy?',
    storyTitle: 'The Magic Toy Box',
    values: 'Sharing toys with friends and tidying up together',
    concept: 'Toy items, colors, and size comparison (big/small)',
    oracy: 'Describing toys by color and size',
    crossCurricular: 'Design & Social Interaction',
    numeracy: 'Number 7',
    project: 'Toy sorting by color and size box',
    vocabularyReferences: ['car', 'teddy bear', 'doll', 'ball', 'kite', 'tricycle', 'blocks', 'yo-yo', 'train', 'puzzle', 'board game', 'robot'],
    languagePatterns: ['What color is the ball?', 'The ball is red.', 'It\'s red.', 'Is it big?', 'Is it small?', 'Is it red?', 'Is it blue?', 'Is it yellow?', 'Yes, it is.', 'No, it isn\'t.', 'The ball is small and blue.']
  },
  {
    key: 'B1_U8',
    bookNumber: 1,
    unitNumber: 8,
    ageGroupCode: '3-4',
    bigQuestion: 'What can we see in a park?',
    storyTitle: 'Sunny Day at the Park',
    values: 'Appreciating nature and playing safely on playground equipment',
    concept: 'Park elements, insects, and playground equipment',
    oracy: 'Describing scenery and playground preferences',
    crossCurricular: 'Environmental Science',
    numeracy: 'Number 8',
    project: 'Nature leaf and flower rubbing art',
    vocabularyReferences: ['tree', 'flower', 'grass', 'bee', 'slide', 'swing', 'seesaw', 'monkey bars', 'sun', 'cloud', 'sky', 'butterfly'],
    languagePatterns: ['Do you like to play on the swings?', 'Yes, I do.', 'No, I don\'t.', 'What can you see?', 'I can see a butterfly.', 'I can see some clouds.']
  },
  {
    key: 'B1_U9',
    bookNumber: 1,
    unitNumber: 9,
    ageGroupCode: '3-4',
    bigQuestion: 'Where do we live?',
    storyTitle: 'Homes Near and Far',
    values: 'Love for one\'s home and community safety',
    concept: 'City vs country, home structures, and neighborhood places',
    oracy: 'Stating where one lives and naming home parts',
    crossCurricular: 'Geography & Architecture',
    numeracy: 'Numbers 9–10',
    project: 'Cardboard house crafting',
    vocabularyReferences: ['city', 'country', 'house', 'farm', 'apartment building', 'door', 'window', 'street', 'park', 'playground', 'market', 'toy store'],
    languagePatterns: ['Where does s/he live?', 'S/he lives in a house.', 'S/he lives in an apartment building.', 'Where do you live?', 'I live in a/an...', 'What can you see near your house?', 'I can see a park near my house.']
  },

  // ===================== BOOK 2 — AGE 4–5 =====================
  {
    key: 'B2_U1',
    bookNumber: 2,
    unitNumber: 1,
    ageGroupCode: '4-5',
    bigQuestion: 'What do you like about school?',
    storyTitle: 'A Creative Day in Class',
    values: 'Joy in learning, friendship, and teamwork',
    concept: 'Art supplies, school activities, and actions',
    oracy: 'Explaining tool usage and favorite school moments',
    crossCurricular: 'Arts & Craft',
    numeracy: 'Counting 1–10',
    project: 'My favorite school activity poster',
    vocabularyReferences: ['paint', 'draw', 'color', 'cut', 'glue', 'pencil', 'marker', 'paintbrush', 'glue stick', 'scissors', 'listen to stories', 'sing songs', 'tidy up', 'eat lunch', 'play with friends'],
    languagePatterns: ['What is it?', 'It\'s a pencil.', 'What do you do with a pencil?', 'I draw with a pencil.', 'What do you like to do?', 'I like to listen to stories.']
  },
  {
    key: 'B2_U2',
    bookNumber: 2,
    unitNumber: 2,
    ageGroupCode: '4-5',
    bigQuestion: 'How do we take care of ourselves?',
    storyTitle: 'Super Healthy Kids',
    values: 'Personal hygiene, hydration, and self-discipline',
    concept: 'Daily self-care rituals, grooming items, and physical states',
    oracy: 'Expressing bodily needs and healthy routines',
    crossCurricular: 'Health & Physical Education',
    numeracy: 'Numbers 11–12',
    project: 'Daily hygiene check checklist',
    vocabularyReferences: ['wash my face', 'brush my hair', 'eat healthy food', 'put on a jacket', 'drink water', 'toothbrush', 'brush', 'soap', 'towel', 'jump rope', 'tired', 'thirsty', 'dirty', 'hungry', 'sick'],
    languagePatterns: ['How do we take care of ourselves?', 'I wash my face.', 'I brush my teeth.', 'Are you thirsty?', 'Yes, I am.', 'Drink some water.']
  },
  {
    key: 'B2_U3',
    bookNumber: 2,
    unitNumber: 3,
    ageGroupCode: '4-5',
    bigQuestion: 'What do we do at home?',
    storyTitle: 'Helping Hands at Home',
    values: 'Helping parents, cleanliness, and family cooperation',
    concept: 'Rooms in a house, home furniture, and household chores',
    oracy: 'Describing room locations and household duties',
    crossCurricular: 'Social Studies',
    numeracy: 'Numbers 13–15',
    project: 'Map of my dream house',
    vocabularyReferences: ['living room', 'dining room', 'kitchen', 'bedroom', 'bathroom', 'bed', 'couch', 'shower', 'lamp', 'fridge', 'cook', 'sweep the floor', 'set the table', 'watch TV', 'make the bed'],
    languagePatterns: ['Where is the lamp?', 'It\'s in the living room.', 'What do you do at home?', 'I set the table.', 'She cooks in the kitchen.']
  },
  {
    key: 'B2_U4',
    bookNumber: 2,
    unitNumber: 4,
    ageGroupCode: '4-5',
    bigQuestion: 'What can we see on a farm?',
    storyTitle: 'Farm Adventures',
    values: 'Respect for farmers and care for farm animals',
    concept: 'Farm animals, baby animals, and farm chores',
    oracy: 'Distinguishing adult animals from their young',
    crossCurricular: 'Agricultural Science & Biology',
    numeracy: 'Numbers 16–18',
    project: 'Farm animal family matching book',
    vocabularyReferences: ['cow', 'hen', 'duck', 'horse', 'sheep', 'feed the ducks', 'milk the cows', 'groom the horses', 'shear the sheep', 'collect the eggs', 'calf', 'lamb', 'duckling', 'chick', 'foal'],
    languagePatterns: ['What can you see on a farm?', 'I can see a cow and a calf.', 'Can you feed the ducks?', 'Yes, I can.', 'A baby duck is a duckling.']
  },
  {
    key: 'B2_U5',
    bookNumber: 2,
    unitNumber: 5,
    ageGroupCode: '4-5',
    bigQuestion: 'What do we eat at different time of the day?',
    storyTitle: 'Three Balanced Meals',
    values: 'Balanced nutrition, table manners, and gratitude for meals',
    concept: 'Meals (breakfast, lunch, dinner) and mealtime foods',
    oracy: 'Explaining meals eaten throughout the day',
    crossCurricular: 'Nutrition & Health',
    numeracy: 'Number 19',
    project: 'Daily meal menu plate design',
    vocabularyReferences: ['breakfast', 'lunch', 'dinner', 'eggs', 'chicken', 'salad', 'pancakes', 'water', 'soup', 'rice', 'milk', 'cereal', 'orange juice', 'fish', 'strawberries'],
    languagePatterns: ['What do you eat for breakfast?', 'I eat eggs and pancakes.', 'What do we eat for dinner?', 'We eat soup and rice.']
  },
  {
    key: 'B2_U6',
    bookNumber: 2,
    unitNumber: 6,
    ageGroupCode: '4-5',
    bigQuestion: 'What different kinds of clothes do we wear?',
    storyTitle: 'Dressing for the Weather',
    values: 'Independence in getting dressed and weather preparedness',
    concept: 'Clothing garments and seasonal weather types',
    oracy: 'Connecting appropriate clothing to current weather',
    crossCurricular: 'Meteorology & Fashion',
    numeracy: 'Number 20',
    project: 'Paper doll weather dressing activity',
    vocabularyReferences: ['pants', 'shoes', 'T-shirt', 'skirt', 'sweater', 'socks', 'jacket', 'boots', 'raincoat', 'dress', 'sunny', 'cloudy', 'rainy', 'snowy', 'windy'],
    languagePatterns: ['What are you wearing?', 'I\'m wearing a yellow T-shirt.', 'It\'s rainy today.', 'Put on your raincoat and boots.']
  },
  {
    key: 'B2_U7',
    bookNumber: 2,
    unitNumber: 7,
    ageGroupCode: '4-5',
    bigQuestion: 'What can we do with our senses?',
    storyTitle: 'Exploring the World with Five Senses',
    values: 'Appreciation of sensory richness and mindfulness',
    concept: 'The 5 sensory organs and descriptive sensory adjectives',
    oracy: 'Describing how things look, feel, sound, taste, and smell',
    crossCurricular: 'Human Biology',
    numeracy: 'Number 30',
    project: 'Mystery sensory touch and smell box',
    vocabularyReferences: ['see', 'touch', 'hear', 'smell', 'taste', 'soft', 'rough', 'smooth', 'good', 'bad', 'sweet', 'salty', 'loud', 'quiet', 'beautiful'],
    languagePatterns: ['What can you do with your eyes?', 'I can see beautiful flowers.', 'How does the lemon taste?', 'It tastes sour and sweet.', 'The music is loud.']
  },
  {
    key: 'B2_U8',
    bookNumber: 2,
    unitNumber: 8,
    ageGroupCode: '4-5',
    bigQuestion: 'How do we get from one place to another?',
    storyTitle: 'Journey Across Land, Water, and Sky',
    values: 'Travel curiosity and traffic safety',
    concept: 'Modes of transport (air, water, land) and destination places',
    oracy: 'Choosing vehicles for various destinations',
    crossCurricular: 'Transportation & Physics',
    numeracy: 'Number 40',
    project: 'Toy vehicle transportation sorting map',
    vocabularyReferences: ['car', 'train', 'bus', 'airplane', 'boat', 'bike', 'helicopter', 'ship', 'air', 'water', 'land', 'beach', 'amusement park', 'mountains', 'city'],
    languagePatterns: ['How do we get to the beach?', 'We go by car.', 'An airplane flies in the air.', 'A boat travels on water.']
  },
  {
    key: 'B2_U9',
    bookNumber: 2,
    unitNumber: 9,
    ageGroupCode: '4-5',
    bigQuestion: 'What do plants need to grow?',
    storyTitle: 'The Secret of the Tiny Seed',
    values: 'Patience, caring for plants, and environmental respect',
    concept: 'Plant anatomy, growth requirements, and gardening tools',
    oracy: 'Sequencing the life cycle of a plant',
    crossCurricular: 'Botany & Earth Science',
    numeracy: 'Number 50',
    project: 'Plant a bean seed in a cup and observe growth',
    vocabularyReferences: ['plant', 'sun', 'soil', 'water', 'air', 'seed', 'shovel', 'hole', 'watering can', 'petals', 'leaves', 'stem', 'roots'],
    languagePatterns: ['What do plants need to grow?', 'Plants need sun, soil, water, and air.', 'The flower has red petals and green leaves.']
  },

  // ===================== BOOK 3 — AGE 5–6 =====================
  {
    key: 'B3_U1',
    bookNumber: 3,
    unitNumber: 1,
    ageGroupCode: '5-6',
    bigQuestion: 'What do we do at school?',
    storyTitle: 'Our Busy School Week',
    values: 'Time organization, curiosity in diverse subjects',
    concept: 'Days of the week, school subjects, and classroom actions',
    oracy: 'Conversing about daily school timetables and preferences',
    crossCurricular: 'Social Studies & Logic',
    numeracy: 'Counting 1–20',
    project: 'Weekly school schedule planner',
    vocabularyReferences: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Science', 'Art', 'Math', 'Writing', 'Reading', 'Physical Education', 'use a computer', 'play music', 'speak English', 'paint with watercolors', 'read books', 'play in the playground'],
    languagePatterns: ['What do we do on Monday?', 'We have Math and Science on Monday.', 'I like to speak English and play music.']
  },
  {
    key: 'B3_U2',
    bookNumber: 3,
    unitNumber: 2,
    ageGroupCode: '5-6',
    bigQuestion: 'How can we show our feelings?',
    storyTitle: 'Birthday Surprise and Many Emotions',
    values: 'Emotional awareness, empathy, and positive celebration',
    concept: 'Complex emotions, physical expressions, and birthday celebrations',
    oracy: 'Explaining reasons for feeling particular emotions',
    crossCurricular: 'Social-Emotional Learning',
    numeracy: 'Number 30',
    project: 'Emotion comic strip drawing',
    vocabularyReferences: ['shy', 'silly', 'scared', 'excited', 'surprised', 'bored', 'scream', 'jump up and down', 'shout hooray', 'yawn', 'cry', 'laugh', 'candy', 'cake', 'candle', 'balloon', 'present', 'party hat'],
    languagePatterns: ['How do you show you are excited?', 'When I am excited, I jump up and down!', 'Why is he surprised?', 'Because he got a big present!']
  },
  {
    key: 'B3_U3',
    bookNumber: 3,
    unitNumber: 3,
    ageGroupCode: '5-6',
    bigQuestion: 'How are we the same or different?',
    storyTitle: 'All of Us Are Unique!',
    values: 'Embracing diversity, kindness, and inclusive play',
    concept: 'Physical descriptions, extended family relations, and hair styles',
    oracy: 'Respectfully describing similarities and differences among people',
    crossCurricular: 'Anthropology & Sociology',
    numeracy: 'Number 40',
    project: 'Portrait gallery of my friends and relatives',
    vocabularyReferences: ['child', 'children', 'woman', 'women', 'man', 'men', 'tall', 'short', 'thin', 'aunt', 'cousin', 'uncle', 'blond', 'red', 'long', 'curly', 'straight'],
    languagePatterns: ['How are we the same or different?', 'She has long curly hair.', 'He is tall and has blond hair.', 'We both like drawing.']
  },
  {
    key: 'B3_U4',
    bookNumber: 3,
    unitNumber: 4,
    ageGroupCode: '5-6',
    bigQuestion: 'What is a wild animal?',
    storyTitle: 'Wild Safari Expedition',
    values: 'Wildlife conservation and animal habitat protection',
    concept: 'Wild animals, specialized body parts (paw, beak, fin, trunk), and habitats',
    oracy: 'Giving informative descriptions of wild animal features',
    crossCurricular: 'Zoology & Ecology',
    numeracy: 'Number 50',
    project: 'Wild animal habitat diorama',
    vocabularyReferences: ['monkey', 'lion', 'giraffe', 'tiger', 'bear', 'elephant', 'snake', 'whale', 'eagle', 'shark', 'kangaroo', 'toucan', 'paw', 'fin', 'beak', 'trunk', 'tail', 'wing'],
    languagePatterns: ['What is a wild animal?', 'An elephant is a wild animal with a long trunk.', 'An eagle has strong wings and a sharp beak.', 'Sharks have fins and swim in the ocean.']
  },
  {
    key: 'B3_U5',
    bookNumber: 3,
    unitNumber: 5,
    ageGroupCode: '5-6',
    bigQuestion: 'Who works in our community?',
    storyTitle: 'Community Helpers to the Rescue',
    values: 'Gratitude for public workers and career aspiration',
    concept: 'Professions, community workplaces, and community roles',
    oracy: 'Discussing who helpers are and what careers children aspire to',
    crossCurricular: 'Civics & Economics',
    numeracy: 'Number 60',
    project: 'Community helper role-play interview',
    vocabularyReferences: ['firefighter', 'doctor', 'chef', 'police officer', 'mail carrier', 'cashier', 'fire station', 'hospital', 'restaurant', 'post office', 'police station', 'grocery store', 'put out fires', 'take care of people', 'cook food', 'keep people safe', 'deliver mail', 'ring up groceries'],
    languagePatterns: ['Who works in our community?', 'A firefighter puts out fires at the fire station.', 'A doctor takes care of people in the hospital.', 'I want to be a chef because I love cooking food.']
  },
  {
    key: 'B3_U6',
    bookNumber: 3,
    unitNumber: 6,
    ageGroupCode: '5-6',
    bigQuestion: 'Why are restaurants special?',
    storyTitle: 'Dinner at the Sunny Bistro',
    values: 'Polite dining etiquette and cultural food appreciation',
    concept: 'Restaurant roles, menu structure (main dish, side, dessert), and ordering',
    oracy: 'Politely ordering food and expressing meal preferences',
    crossCurricular: 'Culinary Arts & Social Etiquette',
    numeracy: 'Number 70',
    project: 'Create and illustrate a restaurant menu',
    vocabularyReferences: ['waiter', 'menu', 'drink', 'main dish', 'side dish', 'dessert', 'steak', 'beans', 'lemonade', 'rice', 'soda', 'French fries', 'spaghetti', 'pizza', 'ice cream', 'chocolate cake', 'vegetables', 'cheeseburger'],
    languagePatterns: ['Why are restaurants special?', 'May I have the menu, please?', 'I would like spaghetti and lemonade for my meal.', 'For dessert, I love chocolate cake and ice cream.']
  },
  {
    key: 'B3_U7',
    bookNumber: 3,
    unitNumber: 7,
    ageGroupCode: '5-6',
    bigQuestion: 'What does a routine look like?',
    storyTitle: 'From Dawn to Dusk: A Healthy Routine',
    values: 'Time management, consistency, and healthy sleep habits',
    concept: 'Chronological morning, afternoon, and night daily routines',
    oracy: 'Narrating sequential daily routines with transition words',
    crossCurricular: 'Time & Health Management',
    numeracy: 'Number 80',
    project: 'My 24-hour routine clock craft',
    vocabularyReferences: ['get up', 'get dressed', 'have breakfast', 'go to school', 'go home', 'do homework', 'dance class', 'soccer practice', 'music lessons', 'swimming lessons', 'play with friends', 'gymnastics', 'eat dinner', 'take a bath', 'brush teeth', 'put on pajamas', 'read a book', 'go to bed'],
    languagePatterns: ['What does your routine look like?', 'First, I get up and get dressed.', 'After school, I go to soccer practice and do homework.', 'At night, I brush my teeth and go to bed.']
  },
  {
    key: 'B3_U8',
    bookNumber: 3,
    unitNumber: 8,
    ageGroupCode: '5-6',
    bigQuestion: 'How can we care for the Earth?',
    storyTitle: 'Earth Protectors Club',
    values: 'Environmental stewardship, recycling, and conserving energy',
    concept: 'Natural vs human-made materials, waste sorting, and conservation',
    oracy: 'Explaining environmental rules and eco-friendly choices',
    crossCurricular: 'Environmental Science & Sustainability',
    numeracy: 'Number 90',
    project: 'Recycled art sculpture from clean cartons',
    vocabularyReferences: ['natural', 'human-made', 'frog', 'rock', 'paper', 'plastic bottle', 'cardboard box', 'soda can', 'newspaper', 'spoon', 'jar', 'glass bottle', 'plastic bag', 'cloth bag', 'recycle', 'trash', 'turn on', 'turn off'],
    languagePatterns: ['How can we care for the Earth?', 'We can recycle plastic bottles and cardboard boxes.', 'Turn off the lights when you leave the room.', 'Use cloth bags instead of plastic bags.']
  },
  {
    key: 'B3_U9',
    bookNumber: 3,
    unitNumber: 9,
    ageGroupCode: '5-6',
    bigQuestion: 'What do we do on vacation?',
    storyTitle: 'Unforgettable Vacation Travels',
    values: 'Spirit of exploration, teamwork, and love of nature',
    concept: 'Vacation destinations, travel equipment, and recreational activities',
    oracy: 'Sharing vacation plans and storytelling vacation memories',
    crossCurricular: 'Geography & Recreation',
    numeracy: 'Number 100',
    project: 'Vacation travel brochure and postcard',
    vocabularyReferences: ['beach', 'mountains', 'forest', 'amusement park', 'lake', 'summer camp', 'towel', 'flashlight', 'sleeping bag', 'sunglasses', 'cap', 'backpack', 'build a sandcastle', 'hike', 'make a campfire', 'go on rides', 'row a boat', 'ride a horse'],
    languagePatterns: ['What do you do on vacation?', 'We go to the mountains to hike and make a campfire.', 'On the beach, I wear sunglasses and build a sandcastle.', 'I would love to go to summer camp.']
  }
];

module.exports = {
  AGE_GROUPS_DATA,
  BOOKS_DATA,
  UNITS_DATA
};
