/**
 * Complete Vocabulary Dataset for KCEnglishKids (27 Units)
 * Deduplicated, reusable vocabulary items with simple Vietnamese definitions,
 * phonetic transcriptions, topics, media keys, and source unit mappings.
 */

const RAW_VOCABULARY = [
  // ==================== BOOK 1 (AGE 3-4) ====================
  // B1_U1 (School)
  { en: 'teacher', vi: 'Giáo viên', ipa: '/ˈtiː.tʃər/', pos: 'noun', units: ['B1_U1'], ages: ['3-4'], topics: ['school'], cat: 'people' },
  { en: 'boy', vi: 'Cậu bé', ipa: '/bɔɪ/', pos: 'noun', units: ['B1_U1'], ages: ['3-4'], topics: ['school'], cat: 'people' },
  { en: 'girl', vi: 'Cô bé', ipa: '/ɡɜːl/', pos: 'noun', units: ['B1_U1'], ages: ['3-4'], topics: ['school'], cat: 'people' },
  { en: 'school', vi: 'Trường học', ipa: '/skuːl/', pos: 'noun', units: ['B1_U1'], ages: ['3-4'], topics: ['school'], cat: 'places' },
  { en: 'sun', vi: 'Mặt trời', ipa: '/sʌn/', pos: 'noun', units: ['B1_U1', 'B1_U8', 'B2_U9'], ages: ['3-4', '4-5'], topics: ['nature', 'weather'], cat: 'nature' },
  { en: 'tree', vi: 'Cái cây', ipa: '/triː/', pos: 'noun', units: ['B1_U1', 'B1_U8', 'B2_U9'], ages: ['3-4', '4-5'], topics: ['nature'], cat: 'nature' },
  { en: 'book', vi: 'Quyển sách', ipa: '/bʊk/', pos: 'noun', units: ['B1_U1'], ages: ['3-4'], topics: ['school'], cat: 'objects' },
  { en: 'crayon', vi: 'Bút sáp màu', ipa: '/ˈkreɪ.ɒn/', pos: 'noun', units: ['B1_U1'], ages: ['3-4'], topics: ['school', 'colors'], cat: 'objects' },
  { en: 'chair', vi: 'Cái ghế', ipa: '/tʃeər/', pos: 'noun', units: ['B1_U1'], ages: ['3-4'], topics: ['school', 'my-house'], cat: 'objects' },
  { en: 'table', vi: 'Cái bàn', ipa: '/ˈteɪ.bəl/', pos: 'noun', units: ['B1_U1'], ages: ['3-4'], topics: ['school', 'my-house'], cat: 'objects' },
  { en: 'Leo', vi: 'Bạn Leo', ipa: '/ˈliː.oʊ/', pos: 'noun', units: ['B1_U1'], ages: ['3-4'], topics: ['school'], cat: 'people' },
  { en: 'Tickles', vi: 'Bạn Tickles', ipa: '/ˈtɪk.əlz/', pos: 'noun', units: ['B1_U1'], ages: ['3-4'], topics: ['school'], cat: 'people' },
  { en: 'Dad', vi: 'Bố', ipa: '/dæd/', pos: 'noun', units: ['B1_U1', 'B1_U4'], ages: ['3-4'], topics: ['family'], cat: 'family' },
  { en: 'Mom', vi: 'Mẹ', ipa: '/mɒm/', pos: 'noun', units: ['B1_U1', 'B1_U4'], ages: ['3-4'], topics: ['family'], cat: 'family' },
  { en: 'Mia', vi: 'Bạn Mia', ipa: '/ˈmiː.ə/', pos: 'noun', units: ['B1_U1'], ages: ['3-4'], topics: ['school'], cat: 'people' },

  // B1_U2 (My Face & Feelings)
  { en: 'face', vi: 'Khuôn mặt', ipa: '/feɪs/', pos: 'noun', units: ['B1_U2'], ages: ['3-4'], topics: ['my-body'], cat: 'body' },
  { en: 'hair', vi: 'Mái tóc', ipa: '/heər/', pos: 'noun', units: ['B1_U2', 'B3_U3'], ages: ['3-4', '5-6'], topics: ['my-body'], cat: 'body' },
  { en: 'eyes', vi: 'Đôi mắt', ipa: '/aɪz/', pos: 'noun', units: ['B1_U2'], ages: ['3-4'], topics: ['my-body', 'senses'], cat: 'body' },
  { en: 'nose', vi: 'Chiếc mũi', ipa: '/nəʊz/', pos: 'noun', units: ['B1_U2'], ages: ['3-4'], topics: ['my-body', 'senses'], cat: 'body' },
  { en: 'forehead', vi: 'Vầng trán', ipa: '/ˈfɔː.hed/', pos: 'noun', units: ['B1_U2'], ages: ['3-4'], topics: ['my-body'], cat: 'body' },
  { en: 'mouth', vi: 'Miệng', ipa: '/maʊθ/', pos: 'noun', units: ['B1_U2'], ages: ['3-4'], topics: ['my-body', 'senses'], cat: 'body' },
  { en: 'ears', vi: 'Đôi tai', ipa: '/ɪəz/', pos: 'noun', units: ['B1_U2'], ages: ['3-4'], topics: ['my-body', 'senses'], cat: 'body' },
  { en: 'cheeks', vi: 'Đôi má', ipa: '/tʃiːks/', pos: 'noun', units: ['B1_U2'], ages: ['3-4'], topics: ['my-body'], cat: 'body' },
  { en: 'happy', vi: 'Vui vẻ', ipa: '/ˈhæp.i/', pos: 'adjective', units: ['B1_U2'], ages: ['3-4'], topics: ['feelings'], cat: 'feelings' },
  { en: 'sad', vi: 'Buồn bã', ipa: '/sæd/', pos: 'adjective', units: ['B1_U2'], ages: ['3-4'], topics: ['feelings'], cat: 'feelings' },
  { en: 'angry', vi: 'Tức giận', ipa: '/ˈæŋ.ɡri/', pos: 'adjective', units: ['B1_U2'], ages: ['3-4'], topics: ['feelings'], cat: 'feelings' },

  // B1_U3 (Body Movements)
  { en: 'arms', vi: 'Cánh tay', ipa: '/ɑːmz/', pos: 'noun', units: ['B1_U3'], ages: ['3-4'], topics: ['my-body'], cat: 'body' },
  { en: 'hands', vi: 'Bàn tay', ipa: '/hændz/', pos: 'noun', units: ['B1_U3'], ages: ['3-4'], topics: ['my-body'], cat: 'body' },
  { en: 'legs', vi: 'Đôi chân', ipa: '/leɡz/', pos: 'noun', units: ['B1_U3'], ages: ['3-4'], topics: ['my-body'], cat: 'body' },
  { en: 'feet', vi: 'Bàn chân', ipa: '/fiːt/', pos: 'noun', units: ['B1_U3'], ages: ['3-4'], topics: ['my-body'], cat: 'body' },
  { en: 'fingers', vi: 'Ngón tay', ipa: '/ˈfɪŋ.ɡərz/', pos: 'noun', units: ['B1_U3'], ages: ['3-4'], topics: ['my-body'], cat: 'body' },
  { en: 'head', vi: 'Cái đầu', ipa: '/hed/', pos: 'noun', units: ['B1_U3'], ages: ['3-4'], topics: ['my-body'], cat: 'body' },
  { en: 'elbow', vi: 'Khuỷu tay', ipa: '/ˈel.bəʊ/', pos: 'noun', units: ['B1_U3'], ages: ['3-4'], topics: ['my-body'], cat: 'body' },
  { en: 'knee', vi: 'Đầu gối', ipa: '/niː/', pos: 'noun', units: ['B1_U3'], ages: ['3-4'], topics: ['my-body'], cat: 'body' },
  { en: 'run', vi: 'Chạy', ipa: '/rʌn/', pos: 'verb', units: ['B1_U3'], ages: ['3-4'], topics: ['my-body'], cat: 'actions' },
  { en: 'dance', vi: 'Nhảy múa', ipa: '/dɑːns/', pos: 'verb', units: ['B1_U3'], ages: ['3-4'], topics: ['my-body'], cat: 'actions' },
  { en: 'crawl', vi: 'Bò', ipa: '/krɔːl/', pos: 'verb', units: ['B1_U3'], ages: ['3-4'], topics: ['my-body'], cat: 'actions' },
  { en: 'kick', vi: 'Đá', ipa: '/kɪk/', pos: 'verb', units: ['B1_U3'], ages: ['3-4'], topics: ['my-body'], cat: 'actions' },

  // B1_U4 (Family)
  { en: 'family', vi: 'Gia đình', ipa: '/ˈfæm.əl.i/', pos: 'noun', units: ['B1_U4', 'B3_U3'], ages: ['3-4', '5-6'], topics: ['family'], cat: 'family' },
  { en: 'father', vi: 'Bố', ipa: '/ˈfɑː.ðər/', pos: 'noun', units: ['B1_U4'], ages: ['3-4'], topics: ['family'], cat: 'family' },
  { en: 'mother', vi: 'Mẹ', ipa: '/ˈmʌð.ər/', pos: 'noun', units: ['B1_U4'], ages: ['3-4'], topics: ['family'], cat: 'family' },
  { en: 'sister', vi: 'Chị/em gái', ipa: '/ˈsɪs.tər/', pos: 'noun', units: ['B1_U4'], ages: ['3-4'], topics: ['family'], cat: 'family' },
  { en: 'brother', vi: 'Anh/em trai', ipa: '/ˈbrʌð.ər/', pos: 'noun', units: ['B1_U4'], ages: ['3-4'], topics: ['family'], cat: 'family' },
  { en: 'grandfather', vi: 'Ông', ipa: '/ˈɡræn.fɑː.ðər/', pos: 'noun', units: ['B1_U4'], ages: ['3-4'], topics: ['family'], cat: 'family' },
  { en: 'grandmother', vi: 'Bà', ipa: '/ˈɡræn.mʌð.ər/', pos: 'noun', units: ['B1_U4'], ages: ['3-4'], topics: ['family'], cat: 'family' },
  { en: 'baby', vi: 'Em bé', ipa: '/ˈbeɪ.bi/', pos: 'noun', units: ['B1_U4'], ages: ['3-4'], topics: ['family'], cat: 'family' },
  { en: 'young', vi: 'Trẻ', ipa: '/jʌŋ/', pos: 'adjective', units: ['B1_U4'], ages: ['3-4'], topics: ['family'], cat: 'descriptors' },
  { en: 'old', vi: 'Già', ipa: '/əʊld/', pos: 'adjective', units: ['B1_U4'], ages: ['3-4'], topics: ['family'], cat: 'descriptors' },
  { en: 'short', vi: 'Thấp, ngắn', ipa: '/ʃɔːt/', pos: 'adjective', units: ['B1_U4', 'B3_U3'], ages: ['3-4', '5-6'], topics: ['family', 'my-body'], cat: 'descriptors' },
  { en: 'tall', vi: 'Cao', ipa: '/tɔːl/', pos: 'adjective', units: ['B1_U4', 'B3_U3'], ages: ['3-4', '5-6'], topics: ['family', 'my-body'], cat: 'descriptors' },

  // B1_U5 (Pets)
  { en: 'dog', vi: 'Con chó', ipa: '/dɒɡ/', pos: 'noun', units: ['B1_U5'], ages: ['3-4'], topics: ['animals'], cat: 'animals' },
  { en: 'bird', vi: 'Con chim', ipa: '/bɜːd/', pos: 'noun', units: ['B1_U5'], ages: ['3-4'], topics: ['animals'], cat: 'animals' },
  { en: 'rabbit', vi: 'Con thỏ', ipa: '/ˈræb.ɪt/', pos: 'noun', units: ['B1_U5'], ages: ['3-4'], topics: ['animals'], cat: 'animals' },
  { en: 'fish', vi: 'Con cá', ipa: '/fɪʃ/', pos: 'noun', units: ['B1_U5', 'B2_U5'], ages: ['3-4', '4-5'], topics: ['animals', 'food'], cat: 'animals' },
  { en: 'turtle', vi: 'Con rùa', ipa: '/ˈtɜː.təl/', pos: 'noun', units: ['B1_U5'], ages: ['3-4'], topics: ['animals'], cat: 'animals' },
  { en: 'cat', vi: 'Con mèo', ipa: '/kæt/', pos: 'noun', units: ['B1_U5'], ages: ['3-4'], topics: ['animals'], cat: 'animals' },
  { en: 'hamster', vi: 'Chuột hamster', ipa: '/ˈhæm.stər/', pos: 'noun', units: ['B1_U5'], ages: ['3-4'], topics: ['animals'], cat: 'animals' },
  { en: 'lizard', vi: 'Con thằn lằn', ipa: '/ˈlɪz.əd/', pos: 'noun', units: ['B1_U5'], ages: ['3-4'], topics: ['animals'], cat: 'animals' },
  { en: 'walk', vi: 'Đi bộ', ipa: '/wɔːk/', pos: 'verb', units: ['B1_U5'], ages: ['3-4'], topics: ['animals', 'my-body'], cat: 'actions' },
  { en: 'jump', vi: 'Nhảy', ipa: '/dʒʌmp/', pos: 'verb', units: ['B1_U5'], ages: ['3-4'], topics: ['animals', 'my-body'], cat: 'actions' },
  { en: 'swim', vi: 'Bơi', ipa: '/swɪm/', pos: 'verb', units: ['B1_U5'], ages: ['3-4'], topics: ['animals', 'my-body'], cat: 'actions' },
  { en: 'fly', vi: 'Bay', ipa: '/flaɪ/', pos: 'verb', units: ['B1_U5'], ages: ['3-4'], topics: ['animals'], cat: 'actions' },

  // B1_U6 (Healthy Food)
  { en: 'apple', vi: 'Quả táo', ipa: '/ˈæp.əl/', pos: 'noun', units: ['B1_U6'], ages: ['3-4'], topics: ['food'], cat: 'food' },
  { en: 'pear', vi: 'Quả lê', ipa: '/peər/', pos: 'noun', units: ['B1_U6'], ages: ['3-4'], topics: ['food'], cat: 'food' },
  { en: 'tomato', vi: 'Quả cà chua', ipa: '/təˈmɑː.təʊ/', pos: 'noun', units: ['B1_U6'], ages: ['3-4'], topics: ['food'], cat: 'food' },
  { en: 'carrot', vi: 'Củ cà rốt', ipa: '/ˈkær.ət/', pos: 'noun', units: ['B1_U6'], ages: ['3-4'], topics: ['food'], cat: 'food' },
  { en: 'bananas', vi: 'Những quả chuối', ipa: '/bəˈnɑː.nəz/', pos: 'noun', units: ['B1_U6'], ages: ['3-4'], topics: ['food'], cat: 'food' },
  { en: 'grapes', vi: 'Chùm nho', ipa: '/ɡreɪps/', pos: 'noun', units: ['B1_U6'], ages: ['3-4'], topics: ['food'], cat: 'food' },
  { en: 'cucumbers', vi: 'Dưa leo', ipa: '/ˈkjuː.kʌm.bərz/', pos: 'noun', units: ['B1_U6'], ages: ['3-4'], topics: ['food'], cat: 'food' },
  { en: 'lettuce', vi: 'Rau xà lách', ipa: '/ˈlet.ɪs/', pos: 'noun', units: ['B1_U6'], ages: ['3-4'], topics: ['food'], cat: 'food' },
  { en: 'pineapple', vi: 'Quả dứa (thơm)', ipa: '/ˈpaɪnˌæp.əl/', pos: 'noun', units: ['B1_U6'], ages: ['3-4'], topics: ['food'], cat: 'food' },
  { en: 'orange', vi: 'Quả cam', ipa: '/ˈɒr.ɪndʒ/', pos: 'noun', units: ['B1_U6'], ages: ['3-4'], topics: ['food', 'colors'], cat: 'food' },
  { en: 'potato', vi: 'Củ khoai tây', ipa: '/pəˈteɪ.təʊ/', pos: 'noun', units: ['B1_U6'], ages: ['3-4'], topics: ['food'], cat: 'food' },
  { en: 'peas', vi: 'Đậu Hà Lan', ipa: '/piːz/', pos: 'noun', units: ['B1_U6'], ages: ['3-4'], topics: ['food'], cat: 'food' },

  // B1_U7 (Toys)
  { en: 'car', vi: 'Ô tô đồ chơi', ipa: '/kɑːr/', pos: 'noun', units: ['B1_U7', 'B2_U8'], ages: ['3-4', '4-5'], topics: ['toys', 'transportation'], cat: 'toys' },
  { en: 'teddy bear', vi: 'Gấu bông', ipa: '/ˈted.i beər/', pos: 'noun', units: ['B1_U7'], ages: ['3-4'], topics: ['toys'], cat: 'toys' },
  { en: 'doll', vi: 'Búp bê', ipa: '/dɒl/', pos: 'noun', units: ['B1_U7'], ages: ['3-4'], topics: ['toys'], cat: 'toys' },
  { en: 'ball', vi: 'Quả bóng', ipa: '/bɔːl/', pos: 'noun', units: ['B1_U7'], ages: ['3-4'], topics: ['toys'], cat: 'toys' },
  { en: 'kite', vi: 'Cái diều', ipa: '/kaɪt/', pos: 'noun', units: ['B1_U7'], ages: ['3-4'], topics: ['toys'], cat: 'toys' },
  { en: 'tricycle', vi: 'Xe ba bánh', ipa: '/ˈtraɪ.sɪ.kəl/', pos: 'noun', units: ['B1_U7'], ages: ['3-4'], topics: ['toys', 'transportation'], cat: 'toys' },
  { en: 'blocks', vi: 'Khối xếp hình', ipa: '/blɒks/', pos: 'noun', units: ['B1_U7'], ages: ['3-4'], topics: ['toys'], cat: 'toys' },
  { en: 'yo-yo', vi: 'Con quay yo-yo', ipa: '/ˈjəʊ.jəʊ/', pos: 'noun', units: ['B1_U7'], ages: ['3-4'], topics: ['toys'], cat: 'toys' },
  { en: 'train', vi: 'Đoàn tàu', ipa: '/treɪn/', pos: 'noun', units: ['B1_U7', 'B2_U8'], ages: ['3-4', '4-5'], topics: ['toys', 'transportation'], cat: 'transport' },
  { en: 'puzzle', vi: 'Trò chơi ghép hình', ipa: '/ˈpʌz.əl/', pos: 'noun', units: ['B1_U7'], ages: ['3-4'], topics: ['toys'], cat: 'toys' },
  { en: 'board game', vi: 'Trò chơi cờ', ipa: '/ˈbɔːd ˌɡeɪm/', pos: 'noun', units: ['B1_U7'], ages: ['3-4'], topics: ['toys'], cat: 'toys' },
  { en: 'robot', vi: 'Người máy', ipa: '/ˈrəʊ.bɒt/', pos: 'noun', units: ['B1_U7'], ages: ['3-4'], topics: ['toys'], cat: 'toys' },

  // B1_U8 (Park)
  { en: 'flower', vi: 'Bông hoa', ipa: '/flaʊər/', pos: 'noun', units: ['B1_U8', 'B2_U9'], ages: ['3-4', '4-5'], topics: ['nature'], cat: 'nature' },
  { en: 'grass', vi: 'Thảm cỏ', ipa: '/ɡrɑːs/', pos: 'noun', units: ['B1_U8'], ages: ['3-4'], topics: ['nature'], cat: 'nature' },
  { en: 'bee', vi: 'Con ong', ipa: '/biː/', pos: 'noun', units: ['B1_U8'], ages: ['3-4'], topics: ['nature', 'animals'], cat: 'animals' },
  { en: 'slide', vi: 'Cầu trượt', ipa: '/slaɪd/', pos: 'noun', units: ['B1_U8'], ages: ['3-4'], topics: ['nature', 'toys'], cat: 'playground' },
  { en: 'swing', vi: 'Xích đu', ipa: '/swɪŋ/', pos: 'noun', units: ['B1_U8'], ages: ['3-4'], topics: ['nature', 'toys'], cat: 'playground' },
  { en: 'seesaw', vi: 'Bập bênh', ipa: '/ˈsiː.sɔː/', pos: 'noun', units: ['B1_U8'], ages: ['3-4'], topics: ['nature', 'toys'], cat: 'playground' },
  { en: 'monkey bars', vi: 'Thang leo', ipa: '/ˈmʌŋ.ki ˌbɑːz/', pos: 'noun', units: ['B1_U8'], ages: ['3-4'], topics: ['nature', 'toys'], cat: 'playground' },
  { en: 'cloud', vi: 'Đám mây', ipa: '/klaʊd/', pos: 'noun', units: ['B1_U8', 'B2_U6'], ages: ['3-4', '4-5'], topics: ['nature', 'weather'], cat: 'nature' },
  { en: 'sky', vi: 'Bầu trời', ipa: '/skaɪ/', pos: 'noun', units: ['B1_U8'], ages: ['3-4'], topics: ['nature'], cat: 'nature' },
  { en: 'butterfly', vi: 'Con bướm', ipa: '/ˈbʌt.ə.flaɪ/', pos: 'noun', units: ['B1_U8'], ages: ['3-4'], topics: ['nature', 'animals'], cat: 'animals' },

  // B1_U9 (Where We Live)
  { en: 'city', vi: 'Thành phố', ipa: '/ˈsɪt.i/', pos: 'noun', units: ['B1_U9', 'B2_U8'], ages: ['3-4', '4-5'], topics: ['my-house', 'community'], cat: 'places' },
  { en: 'country', vi: 'Nông thôn', ipa: '/ˈkʌn.tri/', pos: 'noun', units: ['B1_U9'], ages: ['3-4'], topics: ['my-house', 'nature'], cat: 'places' },
  { en: 'house', vi: 'Ngôi nhà', ipa: '/haʊs/', pos: 'noun', units: ['B1_U9'], ages: ['3-4'], topics: ['my-house'], cat: 'places' },
  { en: 'farm', vi: 'Nông trại', ipa: '/fɑːm/', pos: 'noun', units: ['B1_U9', 'B2_U4'], ages: ['3-4', '4-5'], topics: ['my-house', 'animals'], cat: 'places' },
  { en: 'apartment building', vi: 'Tòa chung cư', ipa: '/əˈpɑːt.mənt ˌbɪl.dɪŋ/', pos: 'noun', units: ['B1_U9'], ages: ['3-4'], topics: ['my-house'], cat: 'places' },
  { en: 'door', vi: 'Cửa ra vào', ipa: '/dɔːr/', pos: 'noun', units: ['B1_U9'], ages: ['3-4'], topics: ['my-house'], cat: 'objects' },
  { en: 'window', vi: 'Cửa sổ', ipa: '/ˈwɪn.dəʊ/', pos: 'noun', units: ['B1_U9'], ages: ['3-4'], topics: ['my-house'], cat: 'objects' },
  { en: 'street', vi: 'Đường phố', ipa: '/striːt/', pos: 'noun', units: ['B1_U9'], ages: ['3-4'], topics: ['my-house', 'community'], cat: 'places' },
  { en: 'park', vi: 'Công viên', ipa: '/pɑːk/', pos: 'noun', units: ['B1_U9'], ages: ['3-4'], topics: ['my-house', 'nature'], cat: 'places' },
  { en: 'playground', vi: 'Sân chơi', ipa: '/ˈpleɪ.ɡraʊnd/', pos: 'noun', units: ['B1_U9', 'B3_U1'], ages: ['3-4', '5-6'], topics: ['my-house', 'school'], cat: 'places' },
  { en: 'market', vi: 'Khu chợ', ipa: '/ˈmɑː.kɪt/', pos: 'noun', units: ['B1_U9'], ages: ['3-4'], topics: ['my-house', 'community'], cat: 'places' },
  { en: 'toy store', vi: 'Cửa hàng đồ chơi', ipa: '/tɔɪ stɔːr/', pos: 'noun', units: ['B1_U9'], ages: ['3-4'], topics: ['my-house', 'toys'], cat: 'places' },

  // ==================== BOOK 2 (AGE 4-5) ====================
  // B2_U1 (School Tools & Activities)
  { en: 'paint', vi: 'Vẽ màu', ipa: '/peɪnt/', pos: 'verb', units: ['B2_U1'], ages: ['4-5'], topics: ['school', 'colors'], cat: 'art' },
  { en: 'draw', vi: 'Vẽ tranh', ipa: '/drɔː/', pos: 'verb', units: ['B2_U1'], ages: ['4-5'], topics: ['school'], cat: 'art' },
  { en: 'color', vi: 'Tô màu', ipa: '/ˈkʌl.ər/', pos: 'verb', units: ['B2_U1'], ages: ['4-5'], topics: ['school', 'colors'], cat: 'art' },
  { en: 'cut', vi: 'Cắt giấy', ipa: '/kʌt/', pos: 'verb', units: ['B2_U1'], ages: ['4-5'], topics: ['school'], cat: 'actions' },
  { en: 'glue', vi: 'Dán hồ', ipa: '/ɡluː/', pos: 'verb', units: ['B2_U1'], ages: ['4-5'], topics: ['school'], cat: 'art' },
  { en: 'pencil', vi: 'Bút chì', ipa: '/ˈpen.səl/', pos: 'noun', units: ['B2_U1'], ages: ['4-5'], topics: ['school'], cat: 'objects' },
  { en: 'marker', vi: 'Bút dạ màu', ipa: '/ˈmɑː.kər/', pos: 'noun', units: ['B2_U1'], ages: ['4-5'], topics: ['school', 'colors'], cat: 'objects' },
  { en: 'paintbrush', vi: 'Cọ vẽ', ipa: '/ˈpeɪnt.brʌʃ/', pos: 'noun', units: ['B2_U1'], ages: ['4-5'], topics: ['school'], cat: 'objects' },
  { en: 'glue stick', vi: 'Keo dán thỏi', ipa: '/ɡluː stɪk/', pos: 'noun', units: ['B2_U1'], ages: ['4-5'], topics: ['school'], cat: 'objects' },
  { en: 'scissors', vi: 'Cái kéo', ipa: '/ˈsɪz.əz/', pos: 'noun', units: ['B2_U1'], ages: ['4-5'], topics: ['school'], cat: 'objects' },
  { en: 'listen to stories', vi: 'Nghe kể chuyện', ipa: '/ˈlɪs.ən tuː ˈstɔː.riz/', pos: 'phrase', units: ['B2_U1'], ages: ['4-5'], topics: ['school'], cat: 'actions' },
  { en: 'sing songs', vi: 'Hát những bài hát', ipa: '/sɪŋ sɒŋz/', pos: 'phrase', units: ['B2_U1'], ages: ['4-5'], topics: ['school'], cat: 'actions' },
  { en: 'tidy up', vi: 'Dọn dẹp gọn gàng', ipa: '/ˈtaɪ.di ʌp/', pos: 'phrase', units: ['B2_U1'], ages: ['4-5'], topics: ['school'], cat: 'actions' },
  { en: 'eat lunch', vi: 'Ăn bữa trưa', ipa: '/iːt lʌntʃ/', pos: 'phrase', units: ['B2_U1'], ages: ['4-5'], topics: ['school', 'food'], cat: 'actions' },
  { en: 'play with friends', vi: 'Chơi cùng bạn bè', ipa: '/pleɪ wɪð frendz/', pos: 'phrase', units: ['B2_U1', 'B3_U7'], ages: ['4-5', '5-6'], topics: ['school', 'daily-routines'], cat: 'actions' },

  // B2_U2 (Self-Care & Healthy Habits)
  { en: 'wash my face', vi: 'Rửa mặt', ipa: '/wɒʃ maɪ feɪs/', pos: 'phrase', units: ['B2_U2'], ages: ['4-5'], topics: ['daily-routines', 'my-body'], cat: 'habits' },
  { en: 'brush my hair', vi: 'Chải tóc', ipa: '/brʌʃ maɪ heər/', pos: 'phrase', units: ['B2_U2'], ages: ['4-5'], topics: ['daily-routines', 'my-body'], cat: 'habits' },
  { en: 'eat healthy food', vi: 'Ăn món bổ dưỡng', ipa: '/iːt ˈhel.θi fuːd/', pos: 'phrase', units: ['B2_U2'], ages: ['4-5'], topics: ['food', 'daily-routines'], cat: 'habits' },
  { en: 'put on a jacket', vi: 'Mặc áo khoác', ipa: '/pʊt ɒn ə ˈdʒæk.ɪt/', pos: 'phrase', units: ['B2_U2', 'B2_U6'], ages: ['4-5'], topics: ['clothes', 'daily-routines'], cat: 'habits' },
  { en: 'drink water', vi: 'Uống nước lọc', ipa: '/drɪŋk ˈwɔː.tər/', pos: 'phrase', units: ['B2_U2'], ages: ['4-5'], topics: ['daily-routines'], cat: 'habits' },
  { en: 'toothbrush', vi: 'Bàn chải đánh răng', ipa: '/ˈtuːθ.brʌʃ/', pos: 'noun', units: ['B2_U2'], ages: ['4-5'], topics: ['daily-routines'], cat: 'objects' },
  { en: 'brush', vi: 'Lược chải', ipa: '/brʌʃ/', pos: 'noun', units: ['B2_U2'], ages: ['4-5'], topics: ['daily-routines'], cat: 'objects' },
  { en: 'soap', vi: 'Bánh xà phòng', ipa: '/səʊp/', pos: 'noun', units: ['B2_U2'], ages: ['4-5'], topics: ['daily-routines'], cat: 'objects' },
  { en: 'towel', vi: 'Khăn tắm', ipa: '/taʊəl/', pos: 'noun', units: ['B2_U2', 'B3_U9'], ages: ['4-5', '5-6'], topics: ['daily-routines', 'vacation'], cat: 'objects' },
  { en: 'jump rope', vi: 'Nhảy dây', ipa: '/dʒʌmp rəʊp/', pos: 'noun', units: ['B2_U2'], ages: ['4-5'], topics: ['my-body', 'toys'], cat: 'actions' },
  { en: 'tired', vi: 'Mệt mỏi', ipa: '/taɪəd/', pos: 'adjective', units: ['B2_U2'], ages: ['4-5'], topics: ['feelings'], cat: 'feelings' },
  { en: 'thirsty', vi: 'Khát nước', ipa: '/ˈθɜː.sti/', pos: 'adjective', units: ['B2_U2'], ages: ['4-5'], topics: ['feelings'], cat: 'feelings' },
  { en: 'dirty', vi: 'Lấm bẩn', ipa: '/ˈdɜː.ti/', pos: 'adjective', units: ['B2_U2'], ages: ['4-5'], topics: ['daily-routines'], cat: 'descriptors' },
  { en: 'hungry', vi: 'Đói bụng', ipa: '/ˈhʌŋ.ɡri/', pos: 'adjective', units: ['B2_U2'], ages: ['4-5'], topics: ['feelings'], cat: 'feelings' },
  { en: 'sick', vi: 'Bị ốm', ipa: '/sɪk/', pos: 'adjective', units: ['B2_U2'], ages: ['4-5'], topics: ['feelings'], cat: 'feelings' },

  // B2_U3 (Home & Chores)
  { en: 'living room', vi: 'Phòng khách', ipa: '/ˈlɪv.ɪŋ ˌruːm/', pos: 'noun', units: ['B2_U3'], ages: ['4-5'], topics: ['my-house'], cat: 'rooms' },
  { en: 'dining room', vi: 'Phòng ăn', ipa: '/ˈdaɪ.nɪŋ ˌruːm/', pos: 'noun', units: ['B2_U3'], ages: ['4-5'], topics: ['my-house'], cat: 'rooms' },
  { en: 'kitchen', vi: 'Nhà bếp', ipa: '/ˈkɪtʃ.ən/', pos: 'noun', units: ['B2_U3'], ages: ['4-5'], topics: ['my-house'], cat: 'rooms' },
  { en: 'bedroom', vi: 'Phòng ngủ', ipa: '/ˈbed.ruːm/', pos: 'noun', units: ['B2_U3'], ages: ['4-5'], topics: ['my-house'], cat: 'rooms' },
  { en: 'bathroom', vi: 'Phòng tắm', ipa: '/ˈbɑːθ.ruːm/', pos: 'noun', units: ['B2_U3'], ages: ['4-5'], topics: ['my-house'], cat: 'rooms' },
  { en: 'bed', vi: 'Chiếc giường', ipa: '/bed/', pos: 'noun', units: ['B2_U3'], ages: ['4-5'], topics: ['my-house'], cat: 'objects' },
  { en: 'couch', vi: 'Ghế sofa', ipa: '/kaʊtʃ/', pos: 'noun', units: ['B2_U3'], ages: ['4-5'], topics: ['my-house'], cat: 'objects' },
  { en: 'shower', vi: 'Vòi hoa sen', ipa: '/ʃaʊər/', pos: 'noun', units: ['B2_U3'], ages: ['4-5'], topics: ['my-house'], cat: 'objects' },
  { en: 'lamp', vi: 'Đèn bàn', ipa: '/læmp/', pos: 'noun', units: ['B2_U3'], ages: ['4-5'], topics: ['my-house'], cat: 'objects' },
  { en: 'fridge', vi: 'Tủ lạnh', ipa: '/frɪdʒ/', pos: 'noun', units: ['B2_U3'], ages: ['4-5'], topics: ['my-house'], cat: 'objects' },
  { en: 'cook', vi: 'Nấu ăn', ipa: '/kʊk/', pos: 'verb', units: ['B2_U3'], ages: ['4-5'], topics: ['my-house', 'food'], cat: 'actions' },
  { en: 'sweep the floor', vi: 'Quét nhà', ipa: '/swiːp ðə flɔːr/', pos: 'phrase', units: ['B2_U3'], ages: ['4-5'], topics: ['my-house'], cat: 'actions' },
  { en: 'set the table', vi: 'Dọn bàn ăn', ipa: '/set ðə ˈteɪ.bəl/', pos: 'phrase', units: ['B2_U3'], ages: ['4-5'], topics: ['my-house'], cat: 'actions' },
  { en: 'watch TV', vi: 'Xem tivi', ipa: '/wɒtʃ ˌtiːˈviː/', pos: 'phrase', units: ['B2_U3'], ages: ['4-5'], topics: ['my-house'], cat: 'actions' },
  { en: 'make the bed', vi: 'Gấp chăn gối', ipa: '/meɪk ðə bed/', pos: 'phrase', units: ['B2_U3'], ages: ['4-5'], topics: ['my-house'], cat: 'actions' },

  // B2_U4 (Farm Animals)
  { en: 'cow', vi: 'Con bò sữa', ipa: '/kaʊ/', pos: 'noun', units: ['B2_U4'], ages: ['4-5'], topics: ['animals'], cat: 'animals' },
  { en: 'hen', vi: 'Con gà mái', ipa: '/hen/', pos: 'noun', units: ['B2_U4'], ages: ['4-5'], topics: ['animals'], cat: 'animals' },
  { en: 'duck', vi: 'Con vịt', ipa: '/dʌk/', pos: 'noun', units: ['B2_U4'], ages: ['4-5'], topics: ['animals'], cat: 'animals' },
  { en: 'horse', vi: 'Con ngựa', ipa: '/hɔːs/', pos: 'noun', units: ['B2_U4'], ages: ['4-5'], topics: ['animals'], cat: 'animals' },
  { en: 'sheep', vi: 'Con cừu', ipa: '/ʃiːp/', pos: 'noun', units: ['B2_U4'], ages: ['4-5'], topics: ['animals'], cat: 'animals' },
  { en: 'feed the ducks', vi: 'Cho vịt ăn', ipa: '/fiːd ðə dʌks/', pos: 'phrase', units: ['B2_U4'], ages: ['4-5'], topics: ['animals'], cat: 'actions' },
  { en: 'milk the cows', vi: 'Vắt sữa bò', ipa: '/mɪlk ðə kaʊz/', pos: 'phrase', units: ['B2_U4'], ages: ['4-5'], topics: ['animals'], cat: 'actions' },
  { en: 'groom the horses', vi: 'Chải lông ngựa', ipa: '/ɡruːm ðə ˈhɔː.sɪz/', pos: 'phrase', units: ['B2_U4'], ages: ['4-5'], topics: ['animals'], cat: 'actions' },
  { en: 'shear the sheep', vi: 'Cắt lông cừu', ipa: '/ʃɪər ðə ʃiːp/', pos: 'phrase', units: ['B2_U4'], ages: ['4-5'], topics: ['animals'], cat: 'actions' },
  { en: 'collect the eggs', vi: 'Nhặt trứng gà', ipa: '/kəˈlekt ði eɡz/', pos: 'phrase', units: ['B2_U4'], ages: ['4-5'], topics: ['animals'], cat: 'actions' },
  { en: 'calf', vi: 'Con bê con', ipa: '/kɑːf/', pos: 'noun', units: ['B2_U4'], ages: ['4-5'], topics: ['animals'], cat: 'animals' },
  { en: 'lamb', vi: 'Cừu non', ipa: '/læm/', pos: 'noun', units: ['B2_U4'], ages: ['4-5'], topics: ['animals'], cat: 'animals' },
  { en: 'duckling', vi: 'Vịt con', ipa: '/ˈdʌk.lɪŋ/', pos: 'noun', units: ['B2_U4'], ages: ['4-5'], topics: ['animals'], cat: 'animals' },
  { en: 'chick', vi: 'Gà con', ipa: '/tʃɪk/', pos: 'noun', units: ['B2_U4'], ages: ['4-5'], topics: ['animals'], cat: 'animals' },
  { en: 'foal', vi: 'Ngựa con', ipa: '/fəʊl/', pos: 'noun', units: ['B2_U4'], ages: ['4-5'], topics: ['animals'], cat: 'animals' },

  // B2_U5 (Daily Meals)
  { en: 'breakfast', vi: 'Bữa sáng', ipa: '/ˈbrek.fəst/', pos: 'noun', units: ['B2_U5', 'B3_U7'], ages: ['4-5', '5-6'], topics: ['food', 'daily-routines'], cat: 'meals' },
  { en: 'lunch', vi: 'Bữa trưa', ipa: '/lʌntʃ/', pos: 'noun', units: ['B2_U5'], ages: ['4-5'], topics: ['food', 'daily-routines'], cat: 'meals' },
  { en: 'dinner', vi: 'Bữa tối', ipa: '/ˈdɪn.ər/', pos: 'noun', units: ['B2_U5', 'B3_U7'], ages: ['4-5', '5-6'], topics: ['food', 'daily-routines'], cat: 'meals' },
  { en: 'eggs', vi: 'Những quả trứng', ipa: '/eɡz/', pos: 'noun', units: ['B2_U5'], ages: ['4-5'], topics: ['food'], cat: 'food' },
  { en: 'chicken', vi: 'Thịt gà', ipa: '/ˈtʃɪk.ɪn/', pos: 'noun', units: ['B2_U5'], ages: ['4-5'], topics: ['food'], cat: 'food' },
  { en: 'salad', vi: 'Món rau trộn', ipa: '/ˈsæl.əd/', pos: 'noun', units: ['B2_U5'], ages: ['4-5'], topics: ['food'], cat: 'food' },
  { en: 'pancakes', vi: 'Bánh kếp nướng', ipa: '/ˈpæn.keɪks/', pos: 'noun', units: ['B2_U5'], ages: ['4-5'], topics: ['food'], cat: 'food' },
  { en: 'water', vi: 'Nước lọc', ipa: '/ˈwɔː.tər/', pos: 'noun', units: ['B2_U5', 'B2_U8', 'B2_U9'], ages: ['4-5'], topics: ['food', 'nature'], cat: 'food' },
  { en: 'soup', vi: 'Bát súp', ipa: '/suːp/', pos: 'noun', units: ['B2_U5'], ages: ['4-5'], topics: ['food'], cat: 'food' },
  { en: 'rice', vi: 'Cơm trắng', ipa: '/raɪs/', pos: 'noun', units: ['B2_U5', 'B3_U6'], ages: ['4-5', '5-6'], topics: ['food'], cat: 'food' },
  { en: 'milk', vi: 'Sữa tươi', ipa: '/mɪlk/', pos: 'noun', units: ['B2_U5'], ages: ['4-5'], topics: ['food'], cat: 'food' },
  { en: 'cereal', vi: 'Ngũ cốc', ipa: '/ˈsɪə.ri.əl/', pos: 'noun', units: ['B2_U5'], ages: ['4-5'], topics: ['food'], cat: 'food' },
  { en: 'orange juice', vi: 'Nước cam ép', ipa: '/ˈɒr.ɪndʒ ˌdʒuːs/', pos: 'noun', units: ['B2_U5'], ages: ['4-5'], topics: ['food'], cat: 'food' },
  { en: 'strawberries', vi: 'Dâu tây', ipa: '/ˈstrɔː.bər.iz/', pos: 'noun', units: ['B2_U5'], ages: ['4-5'], topics: ['food'], cat: 'food' },

  // B2_U6 (Clothes & Weather)
  { en: 'pants', vi: 'Quần dài', ipa: '/pænts/', pos: 'noun', units: ['B2_U6'], ages: ['4-5'], topics: ['clothes'], cat: 'clothes' },
  { en: 'shoes', vi: 'Đôi giày', ipa: '/ʃuːz/', pos: 'noun', units: ['B2_U6'], ages: ['4-5'], topics: ['clothes'], cat: 'clothes' },
  { en: 'T-shirt', vi: 'Áo phông', ipa: '/ˈtiː.ʃɜːt/', pos: 'noun', units: ['B2_U6'], ages: ['4-5'], topics: ['clothes'], cat: 'clothes' },
  { en: 'skirt', vi: 'Chân váy', ipa: '/skɜːt/', pos: 'noun', units: ['B2_U6'], ages: ['4-5'], topics: ['clothes'], cat: 'clothes' },
  { en: 'sweater', vi: 'Áo len', ipa: '/ˈswet.ər/', pos: 'noun', units: ['B2_U6'], ages: ['4-5'], topics: ['clothes'], cat: 'clothes' },
  { en: 'socks', vi: 'Đôi tất', ipa: '/sɒks/', pos: 'noun', units: ['B2_U6'], ages: ['4-5'], topics: ['clothes'], cat: 'clothes' },
  { en: 'jacket', vi: 'Áo khoác', ipa: '/ˈdʒæk.ɪt/', pos: 'noun', units: ['B2_U6'], ages: ['4-5'], topics: ['clothes'], cat: 'clothes' },
  { en: 'boots', vi: 'Đôi ủng', ipa: '/buːts/', pos: 'noun', units: ['B2_U6'], ages: ['4-5'], topics: ['clothes'], cat: 'clothes' },
  { en: 'raincoat', vi: 'Áo mưa', ipa: '/ˈreɪŋ.kəʊt/', pos: 'noun', units: ['B2_U6'], ages: ['4-5'], topics: ['clothes', 'weather'], cat: 'clothes' },
  { en: 'dress', vi: 'Chiếc váy', ipa: '/dres/', pos: 'noun', units: ['B2_U6'], ages: ['4-5'], topics: ['clothes'], cat: 'clothes' },
  { en: 'sunny', vi: 'Có nắng', ipa: '/ˈsʌn.i/', pos: 'adjective', units: ['B2_U6'], ages: ['4-5'], topics: ['weather'], cat: 'weather' },
  { en: 'cloudy', vi: 'Nhiều mây', ipa: '/ˈklaʊ.di/', pos: 'adjective', units: ['B2_U6'], ages: ['4-5'], topics: ['weather'], cat: 'weather' },
  { en: 'rainy', vi: 'Có mưa', ipa: '/ˈreɪ.ni/', pos: 'adjective', units: ['B2_U6'], ages: ['4-5'], topics: ['weather'], cat: 'weather' },
  { en: 'snowy', vi: 'Có tuyết rơi', ipa: '/ˈsnəʊ.i/', pos: 'adjective', units: ['B2_U6'], ages: ['4-5'], topics: ['weather'], cat: 'weather' },
  { en: 'windy', vi: 'Nhiều gió', ipa: '/ˈwɪn.di/', pos: 'adjective', units: ['B2_U6'], ages: ['4-5'], topics: ['weather'], cat: 'weather' },

  // B2_U7 (Senses)
  { en: 'see', vi: 'Nhìn ngắm', ipa: '/siː/', pos: 'verb', units: ['B2_U7'], ages: ['4-5'], topics: ['senses'], cat: 'senses' },
  { en: 'touch', vi: 'Chạm sờ', ipa: '/tʌtʃ/', pos: 'verb', units: ['B2_U7'], ages: ['4-5'], topics: ['senses'], cat: 'senses' },
  { en: 'hear', vi: 'Lắng nghe', ipa: '/hɪər/', pos: 'verb', units: ['B2_U7'], ages: ['4-5'], topics: ['senses'], cat: 'senses' },
  { en: 'smell', vi: 'Ngửi hương', ipa: '/smel/', pos: 'verb', units: ['B2_U7'], ages: ['4-5'], topics: ['senses'], cat: 'senses' },
  { en: 'taste', vi: 'Nếm vị', ipa: '/teɪst/', pos: 'verb', units: ['B2_U7'], ages: ['4-5'], topics: ['senses'], cat: 'senses' },
  { en: 'soft', vi: 'Mềm mại', ipa: '/sɒft/', pos: 'adjective', units: ['B2_U7'], ages: ['4-5'], topics: ['senses'], cat: 'descriptors' },
  { en: 'rough', vi: 'Gồ ghề, ráp', ipa: '/rʌf/', pos: 'adjective', units: ['B2_U7'], ages: ['4-5'], topics: ['senses'], cat: 'descriptors' },
  { en: 'smooth', vi: 'Mịn màng', ipa: '/smuːð/', pos: 'adjective', units: ['B2_U7'], ages: ['4-5'], topics: ['senses'], cat: 'descriptors' },
  { en: 'good', vi: 'Thơm, tốt', ipa: '/ɡʊd/', pos: 'adjective', units: ['B2_U7'], ages: ['4-5'], topics: ['senses'], cat: 'descriptors' },
  { en: 'bad', vi: 'Hôi, dở', ipa: '/bæd/', pos: 'adjective', units: ['B2_U7'], ages: ['4-5'], topics: ['senses'], cat: 'descriptors' },
  { en: 'sweet', vi: 'Ngọt ngào', ipa: '/swiːt/', pos: 'adjective', units: ['B2_U7'], ages: ['4-5'], topics: ['senses', 'food'], cat: 'descriptors' },
  { en: 'salty', vi: 'Mặn mà', ipa: '/ˈsɔːl.ti/', pos: 'adjective', units: ['B2_U7'], ages: ['4-5'], topics: ['senses', 'food'], cat: 'descriptors' },
  { en: 'loud', vi: 'Âm thanh to', ipa: '/laʊd/', pos: 'adjective', units: ['B2_U7'], ages: ['4-5'], topics: ['senses'], cat: 'descriptors' },
  { en: 'quiet', vi: 'Yên tĩnh', ipa: '/ˈkwaɪ.ət/', pos: 'adjective', units: ['B2_U7'], ages: ['4-5'], topics: ['senses'], cat: 'descriptors' },
  { en: 'beautiful', vi: 'Xinh đẹp', ipa: '/ˈbjuː.tɪ.fəl/', pos: 'adjective', units: ['B2_U7'], ages: ['4-5'], topics: ['senses'], cat: 'descriptors' },

  // B2_U8 (Transportation & Travel)
  { en: 'bus', vi: 'Xe buýt', ipa: '/bʌs/', pos: 'noun', units: ['B2_U8'], ages: ['4-5'], topics: ['transportation'], cat: 'transport' },
  { en: 'airplane', vi: 'Máy bay', ipa: '/ˈeə.pleɪn/', pos: 'noun', units: ['B2_U8'], ages: ['4-5'], topics: ['transportation'], cat: 'transport' },
  { en: 'boat', vi: 'Thuyền nhỏ', ipa: '/bəʊt/', pos: 'noun', units: ['B2_U8'], ages: ['4-5'], topics: ['transportation'], cat: 'transport' },
  { en: 'bike', vi: 'Xe đạp', ipa: '/baɪk/', pos: 'noun', units: ['B2_U8'], ages: ['4-5'], topics: ['transportation'], cat: 'transport' },
  { en: 'helicopter', vi: 'Máy bay trực thăng', ipa: '/ˈhel.ɪˌkɒp.tər/', pos: 'noun', units: ['B2_U8'], ages: ['4-5'], topics: ['transportation'], cat: 'transport' },
  { en: 'ship', vi: 'Tàu thuỷ lớn', ipa: '/ʃɪp/', pos: 'noun', units: ['B2_U8'], ages: ['4-5'], topics: ['transportation'], cat: 'transport' },
  { en: 'air', vi: 'Không khí, bầu trời', ipa: '/eər/', pos: 'noun', units: ['B2_U8', 'B2_U9'], ages: ['4-5'], topics: ['transportation', 'nature'], cat: 'nature' },
  { en: 'land', vi: 'Mặt đất', ipa: '/lænd/', pos: 'noun', units: ['B2_U8'], ages: ['4-5'], topics: ['transportation'], cat: 'nature' },
  { en: 'beach', vi: 'Bãi biển', ipa: '/biːtʃ/', pos: 'noun', units: ['B2_U8', 'B3_U9'], ages: ['4-5', '5-6'], topics: ['vacation', 'nature'], cat: 'places' },
  { en: 'amusement park', vi: 'Công viên giải trí', ipa: '/əˈmjuːz.mənt ˌpɑːk/', pos: 'noun', units: ['B2_U8', 'B3_U9'], ages: ['4-5', '5-6'], topics: ['vacation', 'toys'], cat: 'places' },
  { en: 'mountains', vi: 'Dãy núi', ipa: '/ˈmaʊn.tɪnz/', pos: 'noun', units: ['B2_U8', 'B3_U9'], ages: ['4-5', '5-6'], topics: ['vacation', 'nature'], cat: 'places' },

  // B2_U9 (Plants & Growing)
  { en: 'plant', vi: 'Cây cối', ipa: '/plɑːnt/', pos: 'noun', units: ['B2_U9'], ages: ['4-5'], topics: ['nature'], cat: 'nature' },
  { en: 'soil', vi: 'Đất trồng', ipa: '/sɔɪl/', pos: 'noun', units: ['B2_U9'], ages: ['4-5'], topics: ['nature'], cat: 'nature' },
  { en: 'seed', vi: 'Hạt giống', ipa: '/siːd/', pos: 'noun', units: ['B2_U9'], ages: ['4-5'], topics: ['nature'], cat: 'nature' },
  { en: 'shovel', vi: 'Cái xẻng làm vườn', ipa: '/ˈʃʌv.əl/', pos: 'noun', units: ['B2_U9'], ages: ['4-5'], topics: ['nature'], cat: 'tools' },
  { en: 'hole', vi: 'Hố đất', ipa: '/həʊl/', pos: 'noun', units: ['B2_U9'], ages: ['4-5'], topics: ['nature'], cat: 'nature' },
  { en: 'watering can', vi: 'Bình tưới nước', ipa: '/ˈwɔː.tər.ɪŋ ˌkæn/', pos: 'noun', units: ['B2_U9'], ages: ['4-5'], topics: ['nature'], cat: 'tools' },
  { en: 'petals', vi: 'Cánh hoa', ipa: '/ˈpet.əlz/', pos: 'noun', units: ['B2_U9'], ages: ['4-5'], topics: ['nature'], cat: 'nature' },
  { en: 'leaves', vi: 'Những chiếc lá', ipa: '/liːvz/', pos: 'noun', units: ['B2_U9'], ages: ['4-5'], topics: ['nature'], cat: 'nature' },
  { en: 'stem', vi: 'Thân cây', ipa: '/stem/', pos: 'noun', units: ['B2_U9'], ages: ['4-5'], topics: ['nature'], cat: 'nature' },
  { en: 'roots', vi: 'Rễ cây', ipa: '/ruːts/', pos: 'noun', units: ['B2_U9'], ages: ['4-5'], topics: ['nature'], cat: 'nature' },

  // ==================== BOOK 3 (AGE 5-6) ====================
  // B3_U1 (School Subjects & Days)
  { en: 'Monday', vi: 'Thứ Hai', ipa: '/ˈmʌn.deɪ/', pos: 'noun', units: ['B3_U1'], ages: ['5-6'], topics: ['school'], cat: 'calendar' },
  { en: 'Tuesday', vi: 'Thứ Ba', ipa: '/ˈtjuːz.deɪ/', pos: 'noun', units: ['B3_U1'], ages: ['5-6'], topics: ['school'], cat: 'calendar' },
  { en: 'Wednesday', vi: 'Thứ Tư', ipa: '/ˈwenz.deɪ/', pos: 'noun', units: ['B3_U1'], ages: ['5-6'], topics: ['school'], cat: 'calendar' },
  { en: 'Thursday', vi: 'Thứ Năm', ipa: '/ˈθɜːz.deɪ/', pos: 'noun', units: ['B3_U1'], ages: ['5-6'], topics: ['school'], cat: 'calendar' },
  { en: 'Friday', vi: 'Thứ Sáu', ipa: '/ˈfraɪ.deɪ/', pos: 'noun', units: ['B3_U1'], ages: ['5-6'], topics: ['school'], cat: 'calendar' },
  { en: 'Science', vi: 'Môn Khoa học', ipa: '/ˈsaɪ.əns/', pos: 'noun', units: ['B3_U1'], ages: ['5-6'], topics: ['school'], cat: 'subjects' },
  { en: 'Art', vi: 'Môn Mỹ thuật', ipa: '/ɑːt/', pos: 'noun', units: ['B3_U1'], ages: ['5-6'], topics: ['school', 'colors'], cat: 'subjects' },
  { en: 'Math', vi: 'Môn Toán', ipa: '/mæθ/', pos: 'noun', units: ['B3_U1'], ages: ['5-6'], topics: ['school', 'numbers'], cat: 'subjects' },
  { en: 'Writing', vi: 'Tập viết', ipa: '/ˈraɪ.tɪŋ/', pos: 'noun', units: ['B3_U1'], ages: ['5-6'], topics: ['school'], cat: 'subjects' },
  { en: 'Reading', vi: 'Tập đọc', ipa: '/ˈriː.dɪŋ/', pos: 'noun', units: ['B3_U1'], ages: ['5-6'], topics: ['school'], cat: 'subjects' },
  { en: 'Physical Education', vi: 'Môn Thể dục', ipa: '/ˌfɪz.ɪ.kəl ed.jʊˈkeɪ.ʃən/', pos: 'noun', units: ['B3_U1'], ages: ['5-6'], topics: ['school', 'my-body'], cat: 'subjects' },
  { en: 'use a computer', vi: 'Dùng máy vi tính', ipa: '/juːz ə kəmˈpjuː.tər/', pos: 'phrase', units: ['B3_U1'], ages: ['5-6'], topics: ['school'], cat: 'actions' },
  { en: 'play music', vi: 'Chơi nhạc cụ', ipa: '/pleɪ ˈmjuː.zɪk/', pos: 'phrase', units: ['B3_U1'], ages: ['5-6'], topics: ['school'], cat: 'actions' },
  { en: 'speak English', vi: 'Nói tiếng Anh', ipa: '/spiːk ˈɪŋ.ɡlɪʃ/', pos: 'phrase', units: ['B3_U1'], ages: ['5-6'], topics: ['school'], cat: 'actions' },
  { en: 'paint with watercolors', vi: 'Vẽ màu nước', ipa: '/peɪnt wɪð ˈwɔː.təˌkʌl.ərz/', pos: 'phrase', units: ['B3_U1'], ages: ['5-6'], topics: ['school', 'colors'], cat: 'actions' },
  { en: 'read books', vi: 'Đọc sách truyện', ipa: '/riːd bʊks/', pos: 'phrase', units: ['B3_U1', 'B3_U7'], ages: ['5-6'], topics: ['school', 'daily-routines'], cat: 'actions' },
  { en: 'play in the playground', vi: 'Chơi ở sân trường', ipa: '/pleɪ ɪn ðə ˈpleɪ.ɡraʊnd/', pos: 'phrase', units: ['B3_U1'], ages: ['5-6'], topics: ['school'], cat: 'actions' },

  // B3_U2 (Feelings & Birthday Celebration)
  { en: 'shy', vi: 'Ngượng ngùng, bẽn lẽn', ipa: '/ʃaɪ/', pos: 'adjective', units: ['B3_U2'], ages: ['5-6'], topics: ['feelings'], cat: 'feelings' },
  { en: 'silly', vi: 'Nghịch ngợm, tếu táo', ipa: '/ˈsɪl.i/', pos: 'adjective', units: ['B3_U2'], ages: ['5-6'], topics: ['feelings'], cat: 'feelings' },
  { en: 'scared', vi: 'Sợ hãi', ipa: '/skeəd/', pos: 'adjective', units: ['B3_U2'], ages: ['5-6'], topics: ['feelings'], cat: 'feelings' },
  { en: 'excited', vi: 'Hào hứng, phấn khởi', ipa: '/ɪkˈsaɪ.tɪd/', pos: 'adjective', units: ['B3_U2'], ages: ['5-6'], topics: ['feelings'], cat: 'feelings' },
  { en: 'surprised', vi: 'Ngạc nhiên bất ngờ', ipa: '/səˈpraɪzd/', pos: 'adjective', units: ['B3_U2'], ages: ['5-6'], topics: ['feelings'], cat: 'feelings' },
  { en: 'bored', vi: 'Buồn chán', ipa: '/bɔːd/', pos: 'adjective', units: ['B3_U2'], ages: ['5-6'], topics: ['feelings'], cat: 'feelings' },
  { en: 'scream', vi: 'Hét to', ipa: '/skriːm/', pos: 'verb', units: ['B3_U2'], ages: ['5-6'], topics: ['feelings'], cat: 'actions' },
  { en: 'jump up and down', vi: 'Nhảy cẫng lên', ipa: '/dʒʌmp ʌp ənd daʊn/', pos: 'phrase', units: ['B3_U2'], ages: ['5-6'], topics: ['feelings', 'my-body'], cat: 'actions' },
  { en: 'shout hooray', vi: 'Hò reo hoan hô', ipa: '/ʃaʊt hʊˈreɪ/', pos: 'phrase', units: ['B3_U2'], ages: ['5-6'], topics: ['feelings'], cat: 'actions' },
  { en: 'yawn', vi: 'Ngáp ngủ', ipa: '/jɔːn/', pos: 'verb', units: ['B3_U2'], ages: ['5-6'], topics: ['feelings'], cat: 'actions' },
  { en: 'cry', vi: 'Khóc nhè', ipa: '/kraɪ/', pos: 'verb', units: ['B3_U2'], ages: ['5-6'], topics: ['feelings'], cat: 'actions' },
  { en: 'laugh', vi: 'Cười tươi', ipa: '/lɑːf/', pos: 'verb', units: ['B3_U2'], ages: ['5-6'], topics: ['feelings'], cat: 'actions' },
  { en: 'candy', vi: 'Kẹo ngọt', ipa: '/ˈkæn.di/', pos: 'noun', units: ['B3_U2'], ages: ['5-6'], topics: ['food', 'feelings'], cat: 'food' },
  { en: 'cake', vi: 'Bánh sinh nhật', ipa: '/keɪk/', pos: 'noun', units: ['B3_U2'], ages: ['5-6'], topics: ['food', 'feelings'], cat: 'food' },
  { en: 'candle', vi: 'Cây nến', ipa: '/ˈkæn.dəl/', pos: 'noun', units: ['B3_U2'], ages: ['5-6'], topics: ['feelings'], cat: 'objects' },
  { en: 'balloon', vi: 'Quả bóng bay', ipa: '/bəˈluːn/', pos: 'noun', units: ['B3_U2'], ages: ['5-6'], topics: ['toys', 'feelings'], cat: 'toys' },
  { en: 'present', vi: 'Món quà tặng', ipa: '/ˈprez.ənt/', pos: 'noun', units: ['B3_U2'], ages: ['5-6'], topics: ['feelings'], cat: 'objects' },
  { en: 'party hat', vi: 'Chiếc nón sinh nhật', ipa: '/ˈpɑː.ti hæt/', pos: 'noun', units: ['B3_U2'], ages: ['5-6'], topics: ['clothes', 'feelings'], cat: 'clothes' },

  // B3_U3 (Describing People & Hair)
  { en: 'child', vi: 'Một đứa trẻ', ipa: '/tʃaɪld/', pos: 'noun', units: ['B3_U3'], ages: ['5-6'], topics: ['family'], cat: 'people' },
  { en: 'children', vi: 'Các bạn nhỏ', ipa: '/ˈtʃɪl.drən/', pos: 'noun', units: ['B3_U3'], ages: ['5-6'], topics: ['family', 'school'], cat: 'people' },
  { en: 'woman', vi: 'Người phụ nữ', ipa: '/ˈwʊm.ən/', pos: 'noun', units: ['B3_U3'], ages: ['5-6'], topics: ['family'], cat: 'people' },
  { en: 'women', vi: 'Những người phụ nữ', ipa: '/ˈwɪm.ɪn/', pos: 'noun', units: ['B3_U3'], ages: ['5-6'], topics: ['family'], cat: 'people' },
  { en: 'man', vi: 'Người đàn ông', ipa: '/mæn/', pos: 'noun', units: ['B3_U3'], ages: ['5-6'], topics: ['family'], cat: 'people' },
  { en: 'men', vi: 'Những người đàn ông', ipa: '/men/', pos: 'noun', units: ['B3_U3'], ages: ['5-6'], topics: ['family'], cat: 'people' },
  { en: 'thin', vi: 'Mảnh khảnh', ipa: '/θɪn/', pos: 'adjective', units: ['B3_U3'], ages: ['5-6'], topics: ['family', 'my-body'], cat: 'descriptors' },
  { en: 'aunt', vi: 'Cô / Dì / Bác gái', ipa: '/ɑːnt/', pos: 'noun', units: ['B3_U3'], ages: ['5-6'], topics: ['family'], cat: 'family' },
  { en: 'cousin', vi: 'Anh chị em họ', ipa: '/ˈkʌz.ən/', pos: 'noun', units: ['B3_U3'], ages: ['5-6'], topics: ['family'], cat: 'family' },
  { en: 'uncle', vi: 'Chú / Bác trai', ipa: '/ˈʌŋ.kəl/', pos: 'noun', units: ['B3_U3'], ages: ['5-6'], topics: ['family'], cat: 'family' },
  { en: 'blond', vi: 'Tóc vàng hoe', ipa: '/blɒnd/', pos: 'adjective', units: ['B3_U3'], ages: ['5-6'], topics: ['my-body'], cat: 'descriptors' },
  { en: 'red', vi: 'Màu đỏ / Tóc hung đỏ', ipa: '/red/', pos: 'adjective', units: ['B3_U3'], ages: ['5-6'], topics: ['colors', 'my-body'], cat: 'colors' },
  { en: 'long', vi: 'Dài', ipa: '/lɒŋ/', pos: 'adjective', units: ['B3_U3'], ages: ['5-6'], topics: ['my-body'], cat: 'descriptors' },
  { en: 'curly', vi: 'Xoăn gợn sóng', ipa: '/ˈkɜː.li/', pos: 'adjective', units: ['B3_U3'], ages: ['5-6'], topics: ['my-body'], cat: 'descriptors' },
  { en: 'straight', vi: 'Thẳng mượt', ipa: '/streɪt/', pos: 'adjective', units: ['B3_U3'], ages: ['5-6'], topics: ['my-body'], cat: 'descriptors' },

  // B3_U4 (Wild Animals & Parts)
  { en: 'monkey', vi: 'Con khỉ', ipa: '/ˈmʌŋ.ki/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'animals' },
  { en: 'lion', vi: 'Sư tử', ipa: '/ˈlaɪ.ən/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'animals' },
  { en: 'giraffe', vi: 'Hươu cao cổ', ipa: '/dʒɪˈrɑːf/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'animals' },
  { en: 'tiger', vi: 'Con hổ', ipa: '/ˈtaɪ.ɡər/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'animals' },
  { en: 'bear', vi: 'Con gấu', ipa: '/beər/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'animals' },
  { en: 'elephant', vi: 'Con voi', ipa: '/ˈel.ɪ.fənt/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'animals' },
  { en: 'snake', vi: 'Con rắn', ipa: '/sneɪk/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'animals' },
  { en: 'whale', vi: 'Cá voi', ipa: '/weɪl/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'animals' },
  { en: 'eagle', vi: 'Chim đại bàng', ipa: '/ˈiː.ɡəl/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'animals' },
  { en: 'shark', vi: 'Cá mập', ipa: '/ʃɑːk/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'animals' },
  { en: 'kangaroo', vi: 'Chuột túi', ipa: '/ˌkæŋ.ɡərˈuː/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'animals' },
  { en: 'toucan', vi: 'Chim tucăng mỏ lớn', ipa: '/ˈtuː.kæn/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'animals' },
  { en: 'paw', vi: 'Móng vuốt, bàn chân thú', ipa: '/pɔː/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'body' },
  { en: 'fin', vi: 'Vây cá', ipa: '/fɪn/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'body' },
  { en: 'beak', vi: 'Mỏ chim', ipa: '/biːk/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'body' },
  { en: 'trunk', vi: 'Vòi voi', ipa: '/trʌŋk/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'body' },
  { en: 'tail', vi: 'Cái đuôi', ipa: '/teɪl/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'body' },
  { en: 'wing', vi: 'Đôi cánh', ipa: '/wɪŋ/', pos: 'noun', units: ['B3_U4'], ages: ['5-6'], topics: ['animals'], cat: 'body' },

  // B3_U5 (Community Helpers & Jobs)
  { en: 'firefighter', vi: 'Lính cứu hỏa', ipa: '/ˈfaɪəˌfaɪ.tər/', pos: 'noun', units: ['B3_U5'], ages: ['5-6'], topics: ['community'], cat: 'jobs' },
  { en: 'doctor', vi: 'Bác sĩ', ipa: '/ˈdɒk.tər/', pos: 'noun', units: ['B3_U5'], ages: ['5-6'], topics: ['community'], cat: 'jobs' },
  { en: 'chef', vi: 'Đầu bếp', ipa: '/ʃef/', pos: 'noun', units: ['B3_U5'], ages: ['5-6'], topics: ['community', 'food'], cat: 'jobs' },
  { en: 'police officer', vi: 'Cảnh sát', ipa: '/pəˈliːs ˌɒf.ɪ.sər/', pos: 'noun', units: ['B3_U5'], ages: ['5-6'], topics: ['community'], cat: 'jobs' },
  { en: 'mail carrier', vi: 'Người đưa thư', ipa: '/ˈmeɪl ˌkær.i.ər/', pos: 'noun', units: ['B3_U5'], ages: ['5-6'], topics: ['community'], cat: 'jobs' },
  { en: 'cashier', vi: 'Nhân viên thu ngân', ipa: '/kæʃˈɪər/', pos: 'noun', units: ['B3_U5'], ages: ['5-6'], topics: ['community'], cat: 'jobs' },
  { en: 'fire station', vi: 'Trạm cứu hỏa', ipa: '/ˈfaɪə ˌsteɪ.ʃən/', pos: 'noun', units: ['B3_U5'], ages: ['5-6'], topics: ['community'], cat: 'places' },
  { en: 'hospital', vi: 'Bệnh viện', ipa: '/ˈhɒs.pɪ.təl/', pos: 'noun', units: ['B3_U5'], ages: ['5-6'], topics: ['community'], cat: 'places' },
  { en: 'restaurant', vi: 'Nhà hàng', ipa: '/ˈres.trɒnt/', pos: 'noun', units: ['B3_U5', 'B3_U6'], ages: ['5-6'], topics: ['community', 'food'], cat: 'places' },
  { en: 'post office', vi: 'Bưu điện', ipa: '/ˈpəʊst ˌɒf.ɪs/', pos: 'noun', units: ['B3_U5'], ages: ['5-6'], topics: ['community'], cat: 'places' },
  { en: 'police station', vi: 'Đồn cảnh sát', ipa: '/pəˈliːs ˌsteɪ.ʃən/', pos: 'noun', units: ['B3_U5'], ages: ['5-6'], topics: ['community'], cat: 'places' },
  { en: 'grocery store', vi: 'Cửa hàng tạp hóa', ipa: '/ˈɡrəʊ.sər.i ˌstɔːr/', pos: 'noun', units: ['B3_U5'], ages: ['5-6'], topics: ['community', 'food'], cat: 'places' },
  { en: 'put out fires', vi: 'Dập tắt đám cháy', ipa: '/pʊt aʊt ˈfaɪəz/', pos: 'phrase', units: ['B3_U5'], ages: ['5-6'], topics: ['community'], cat: 'actions' },
  { en: 'take care of people', vi: 'Chăm sóc mọi người', ipa: '/teɪk keər əv ˈpiː.pəl/', pos: 'phrase', units: ['B3_U5'], ages: ['5-6'], topics: ['community'], cat: 'actions' },
  { en: 'cook food', vi: 'Nấu thức ăn', ipa: '/kʊk fuːd/', pos: 'phrase', units: ['B3_U5'], ages: ['5-6'], topics: ['community', 'food'], cat: 'actions' },
  { en: 'keep people safe', vi: 'Bảo vệ an toàn', ipa: '/kiːp ˈpiː.pəl seɪf/', pos: 'phrase', units: ['B3_U5'], ages: ['5-6'], topics: ['community'], cat: 'actions' },
  { en: 'deliver mail', vi: 'Phát thư và bưu phẩm', ipa: '/dɪˈlɪv.ər meɪl/', pos: 'phrase', units: ['B3_U5'], ages: ['5-6'], topics: ['community'], cat: 'actions' },
  { en: 'ring up groceries', vi: 'Tính tiền hàng', ipa: '/rɪŋ ʌp ˈɡrəʊ.sər.iz/', pos: 'phrase', units: ['B3_U5'], ages: ['5-6'], topics: ['community'], cat: 'actions' },

  // B3_U6 (Restaurants & Menus)
  { en: 'waiter', vi: 'Người phục vụ', ipa: '/ˈweɪ.tər/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food', 'community'], cat: 'jobs' },
  { en: 'menu', vi: 'Thực đơn món ăn', ipa: '/ˈmen.juː/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food'], cat: 'objects' },
  { en: 'drink', vi: 'Đồ uống', ipa: '/drɪŋk/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food'], cat: 'food' },
  { en: 'main dish', vi: 'Món ăn chính', ipa: '/meɪn dɪʃ/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food'], cat: 'food' },
  { en: 'side dish', vi: 'Món ăn phụ', ipa: '/saɪd dɪʃ/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food'], cat: 'food' },
  { en: 'dessert', vi: 'Món tráng miệng', ipa: '/dɪˈzɜːt/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food'], cat: 'food' },
  { en: 'steak', vi: 'Bít tết bò', ipa: '/steɪk/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food'], cat: 'food' },
  { en: 'beans', vi: 'Đậu hạt', ipa: '/biːnz/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food'], cat: 'food' },
  { en: 'lemonade', vi: 'Nước chanh tươi', ipa: '/ˌlem.əˈneɪd/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food'], cat: 'food' },
  { en: 'soda', vi: 'Nước ngọt có ga', ipa: '/ˈsəʊ.də/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food'], cat: 'food' },
  { en: 'French fries', vi: 'Khoai tây chiên', ipa: '/ˌfrentʃ ˈfraɪz/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food'], cat: 'food' },
  { en: 'spaghetti', vi: 'Mì Ý sốt cà', ipa: '/spəˈɡet.i/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food'], cat: 'food' },
  { en: 'pizza', vi: 'Bánh pizza', ipa: '/ˈpiːt.sə/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food'], cat: 'food' },
  { en: 'ice cream', vi: 'Kem mát lạnh', ipa: '/ˈaɪs ˌkriːm/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food'], cat: 'food' },
  { en: 'chocolate cake', vi: 'Bánh kem sô-cô-la', ipa: '/ˈtʃɒk.lət keɪk/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food'], cat: 'food' },
  { en: 'vegetables', vi: 'Các loại rau xanh', ipa: '/ˈvedʒ.tə.bəlz/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food'], cat: 'food' },
  { en: 'cheeseburger', vi: 'Bánh burger phô mai', ipa: '/ˈtʃiːzˌbɜː.ɡər/', pos: 'noun', units: ['B3_U6'], ages: ['5-6'], topics: ['food'], cat: 'food' },

  // B3_U7 (Daily Routines)
  { en: 'get up', vi: 'Thức dậy', ipa: '/ɡet ʌp/', pos: 'phrase', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines'], cat: 'actions' },
  { en: 'get dressed', vi: 'Mặc quần áo', ipa: '/ɡet drest/', pos: 'phrase', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines', 'clothes'], cat: 'actions' },
  { en: 'have breakfast', vi: 'Ăn bữa sáng', ipa: '/hæv ˈbrek.fəst/', pos: 'phrase', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines', 'food'], cat: 'actions' },
  { en: 'go to school', vi: 'Đi đến trường', ipa: '/ɡəʊ tuː skuːl/', pos: 'phrase', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines', 'school'], cat: 'actions' },
  { en: 'go home', vi: 'Trở về nhà', ipa: '/ɡəʊ həʊm/', pos: 'phrase', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines', 'my-house'], cat: 'actions' },
  { en: 'do homework', vi: 'Làm bài tập về nhà', ipa: '/duː ˈhəʊm.wɜːk/', pos: 'phrase', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines', 'school'], cat: 'actions' },
  { en: 'dance class', vi: 'Lớp học múa', ipa: '/dɑːns klɑːs/', pos: 'noun', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines'], cat: 'activities' },
  { en: 'soccer practice', vi: 'Luyện tập đá bóng', ipa: '/ˈsɒk.ər ˌpræk.tɪs/', pos: 'noun', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines'], cat: 'activities' },
  { en: 'music lessons', vi: 'Học đàn, học nhạc', ipa: '/ˈmjuː.zɪk ˌles.ənz/', pos: 'noun', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines'], cat: 'activities' },
  { en: 'swimming lessons', vi: 'Tập bơi', ipa: '/ˈswɪm.ɪŋ ˌles.ənz/', pos: 'noun', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines'], cat: 'activities' },
  { en: 'gymnastics', vi: 'Tập thể dục dụng cụ', ipa: '/dʒɪmˈnæs.tɪks/', pos: 'noun', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines'], cat: 'activities' },
  { en: 'eat dinner', vi: 'Ăn bữa cơm tối', ipa: '/iːt ˈdɪn.ər/', pos: 'phrase', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines', 'food'], cat: 'actions' },
  { en: 'take a bath', vi: 'Tắm rửa sạch sẽ', ipa: '/teɪk ə bɑːθ/', pos: 'phrase', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines'], cat: 'actions' },
  { en: 'brush teeth', vi: 'Đánh răng', ipa: '/brʌʃ tiːθ/', pos: 'phrase', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines'], cat: 'actions' },
  { en: 'put on pajamas', vi: 'Mặc đồ ngủ', ipa: '/pʊt ɒn pəˈdʒɑː.məz/', pos: 'phrase', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines', 'clothes'], cat: 'actions' },
  { en: 'read a book', vi: 'Đọc truyện', ipa: '/riːd ə bʊk/', pos: 'phrase', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines'], cat: 'actions' },
  { en: 'go to bed', vi: 'Lên giường đi ngủ', ipa: '/ɡəʊ tuː bed/', pos: 'phrase', units: ['B3_U7'], ages: ['5-6'], topics: ['daily-routines'], cat: 'actions' },

  // B3_U8 (Caring for Earth & Recycling)
  { en: 'natural', vi: 'Tự nhiên, thiên nhiên', ipa: '/ˈnætʃ.ər.əl/', pos: 'adjective', units: ['B3_U8'], ages: ['5-6'], topics: ['environment', 'nature'], cat: 'descriptors' },
  { en: 'human-made', vi: 'Do con người làm ra', ipa: '/ˌhjuː.mən ˈmeɪd/', pos: 'adjective', units: ['B3_U8'], ages: ['5-6'], topics: ['environment'], cat: 'descriptors' },
  { en: 'frog', vi: 'Chú ếch', ipa: '/frɒɡ/', pos: 'noun', units: ['B3_U8'], ages: ['5-6'], topics: ['environment', 'animals'], cat: 'animals' },
  { en: 'rock', vi: 'Hòn đá', ipa: '/rɒk/', pos: 'noun', units: ['B3_U8'], ages: ['5-6'], topics: ['environment', 'nature'], cat: 'nature' },
  { en: 'paper', vi: 'Giấy viết', ipa: '/ˈpeɪ.pər/', pos: 'noun', units: ['B3_U8'], ages: ['5-6'], topics: ['environment'], cat: 'materials' },
  { en: 'plastic bottle', vi: 'Chai nhựa', ipa: '/ˈplæs.tɪk ˌbɒt.əl/', pos: 'noun', units: ['B3_U8'], ages: ['5-6'], topics: ['environment'], cat: 'materials' },
  { en: 'cardboard box', vi: 'Thùng các-tông', ipa: '/ˈkɑːd.bɔːd bɒks/', pos: 'noun', units: ['B3_U8'], ages: ['5-6'], topics: ['environment'], cat: 'materials' },
  { en: 'soda can', vi: 'Lon nước ngọt', ipa: '/ˈsəʊ.də kæn/', pos: 'noun', units: ['B3_U8'], ages: ['5-6'], topics: ['environment'], cat: 'materials' },
  { en: 'newspaper', vi: 'Tờ báo giấy', ipa: '/ˈnjuːzˌpeɪ.pər/', pos: 'noun', units: ['B3_U8'], ages: ['5-6'], topics: ['environment'], cat: 'materials' },
  { en: 'spoon', vi: 'Cái thìa, muỗng', ipa: '/spuːn/', pos: 'noun', units: ['B3_U8'], ages: ['5-6'], topics: ['environment', 'my-house'], cat: 'objects' },
  { en: 'jar', vi: 'Chiếc lọ thủy tinh', ipa: '/dʒɑːr/', pos: 'noun', units: ['B3_U8'], ages: ['5-6'], topics: ['environment'], cat: 'objects' },
  { en: 'glass bottle', vi: 'Chai thủy tinh', ipa: '/ɡlɑːs ˌbɒt.əl/', pos: 'noun', units: ['B3_U8'], ages: ['5-6'], topics: ['environment'], cat: 'materials' },
  { en: 'plastic bag', vi: 'Túi ni-lông', ipa: '/ˈplæs.tɪk bæɡ/', pos: 'noun', units: ['B3_U8'], ages: ['5-6'], topics: ['environment'], cat: 'materials' },
  { en: 'cloth bag', vi: 'Túi vải bảo vệ môi trường', ipa: '/klɒθ bæɡ/', pos: 'noun', units: ['B3_U8'], ages: ['5-6'], topics: ['environment'], cat: 'materials' },
  { en: 'recycle', vi: 'Tái chế rác', ipa: '/ˌriːˈsaɪ.kəl/', pos: 'verb', units: ['B3_U8'], ages: ['5-6'], topics: ['environment'], cat: 'actions' },
  { en: 'trash', vi: 'Rác thải', ipa: '/træʃ/', pos: 'noun', units: ['B3_U8'], ages: ['5-6'], topics: ['environment'], cat: 'materials' },
  { en: 'turn on', vi: 'Bật công tắc', ipa: '/tɜːn ɒn/', pos: 'phrase', units: ['B3_U8'], ages: ['5-6'], topics: ['environment'], cat: 'actions' },
  { en: 'turn off', vi: 'Tắt đèn, tắt quạt', ipa: '/tɜːn ɒf/', pos: 'phrase', units: ['B3_U8'], ages: ['5-6'], topics: ['environment'], cat: 'actions' },

  // B3_U9 (Vacation & Adventures)
  { en: 'forest', vi: 'Khu rừng rậm', ipa: '/ˈfɒr.ɪst/', pos: 'noun', units: ['B3_U9'], ages: ['5-6'], topics: ['vacation', 'nature'], cat: 'places' },
  { en: 'lake', vi: 'Hồ nước trong xanh', ipa: '/leɪk/', pos: 'noun', units: ['B3_U9'], ages: ['5-6'], topics: ['vacation', 'nature'], cat: 'places' },
  { en: 'summer camp', vi: 'Trại hè thiếu nhi', ipa: '/ˈsʌm.ə ˌkæmp/', pos: 'noun', units: ['B3_U9'], ages: ['5-6'], topics: ['vacation'], cat: 'places' },
  { en: 'flashlight', vi: 'Đèn pin chiếu sáng', ipa: '/ˈflæʃ.laɪt/', pos: 'noun', units: ['B3_U9'], ages: ['5-6'], topics: ['vacation'], cat: 'objects' },
  { en: 'sleeping bag', vi: 'Túi ngủ du lịch', ipa: '/ˈsliː.pɪŋ ˌbæɡ/', pos: 'noun', units: ['B3_U9'], ages: ['5-6'], topics: ['vacation'], cat: 'objects' },
  { en: 'sunglasses', vi: 'Kính râm đi nắng', ipa: '/ˈsʌŋˌɡlɑː.sɪz/', pos: 'noun', units: ['B3_U9'], ages: ['5-6'], topics: ['vacation', 'clothes'], cat: 'objects' },
  { en: 'cap', vi: 'Mũ lưỡi trai', ipa: '/kæp/', pos: 'noun', units: ['B3_U9'], ages: ['5-6'], topics: ['vacation', 'clothes'], cat: 'clothes' },
  { en: 'backpack', vi: 'Ba lô du lịch', ipa: '/ˈbæk.pæk/', pos: 'noun', units: ['B3_U9'], ages: ['5-6'], topics: ['vacation'], cat: 'objects' },
  { en: 'build a sandcastle', vi: 'Xây lâu đài cát', ipa: '/bɪld ə ˈsændˌkɑː.səl/', pos: 'phrase', units: ['B3_U9'], ages: ['5-6'], topics: ['vacation'], cat: 'actions' },
  { en: 'hike', vi: 'Đi bộ leo núi', ipa: '/haɪk/', pos: 'verb', units: ['B3_U9'], ages: ['5-6'], topics: ['vacation'], cat: 'actions' },
  { en: 'make a campfire', vi: 'Đốt lửa trại', ipa: '/meɪk ə ˈkæmp.faɪər/', pos: 'phrase', units: ['B3_U9'], ages: ['5-6'], topics: ['vacation'], cat: 'actions' },
  { en: 'go on rides', vi: 'Chơi trò đu quay cảm giác mạnh', ipa: '/ɡəʊ ɒn raɪdz/', pos: 'phrase', units: ['B3_U9'], ages: ['5-6'], topics: ['vacation'], cat: 'actions' },
  { en: 'row a boat', vi: 'Chèo thuyền trên hồ', ipa: '/rəʊ ə bəʊt/', pos: 'phrase', units: ['B3_U9'], ages: ['5-6'], topics: ['vacation', 'transportation'], cat: 'actions' },
  { en: 'ride a horse', vi: 'Cưỡi ngựa', ipa: '/raɪd ə hɔːs/', pos: 'phrase', units: ['B3_U9'], ages: ['5-6'], topics: ['vacation', 'animals'], cat: 'actions' },

  // ==================== CORE TOPIC: COLORS (Màu sắc) ====================
  { en: 'blue', vi: 'Màu xanh dương', ipa: '/bluː/', pos: 'adjective', units: ['B1_U1', 'B2_U1'], ages: ['3-4', '4-5', '5-6'], topics: ['colors'], cat: 'colors' },
  { en: 'yellow', vi: 'Màu vàng', ipa: '/ˈjel.əʊ/', pos: 'adjective', units: ['B1_U1', 'B2_U1'], ages: ['3-4', '4-5', '5-6'], topics: ['colors'], cat: 'colors' },
  { en: 'green', vi: 'Màu xanh lá', ipa: '/ɡriːn/', pos: 'adjective', units: ['B1_U1', 'B2_U1'], ages: ['3-4', '4-5', '5-6'], topics: ['colors'], cat: 'colors' },
  { en: 'orange', vi: 'Màu cam', ipa: '/ˈɒr.ɪndʒ/', pos: 'adjective', units: ['B1_U1', 'B1_U6'], ages: ['3-4', '4-5', '5-6'], topics: ['colors'], cat: 'colors' },
  { en: 'pink', vi: 'Màu hồng', ipa: '/pɪŋk/', pos: 'adjective', units: ['B1_U1', 'B2_U1'], ages: ['3-4', '4-5', '5-6'], topics: ['colors'], cat: 'colors' },
  { en: 'purple', vi: 'Màu tím', ipa: '/ˈpɜː.pəl/', pos: 'adjective', units: ['B1_U1', 'B2_U1'], ages: ['3-4', '4-5', '5-6'], topics: ['colors'], cat: 'colors' },
  { en: 'brown', vi: 'Màu nâu', ipa: '/braʊn/', pos: 'adjective', units: ['B1_U1', 'B2_U1'], ages: ['3-4', '4-5', '5-6'], topics: ['colors'], cat: 'colors' },
  { en: 'black', vi: 'Màu đen', ipa: '/blæk/', pos: 'adjective', units: ['B1_U1', 'B2_U1'], ages: ['3-4', '4-5', '5-6'], topics: ['colors'], cat: 'colors' },
  { en: 'white', vi: 'Màu trắng', ipa: '/waɪt/', pos: 'adjective', units: ['B1_U1', 'B2_U1'], ages: ['3-4', '4-5', '5-6'], topics: ['colors'], cat: 'colors' },
  { en: 'gray', vi: 'Màu xám', ipa: '/ɡreɪ/', pos: 'adjective', units: ['B1_U1', 'B2_U1'], ages: ['3-4', '4-5', '5-6'], topics: ['colors'], cat: 'colors' },
  { en: 'rainbow', vi: 'Cầu vồng bảy sắc', ipa: '/ˈreɪn.bəʊ/', pos: 'noun', units: ['B1_U1', 'B2_U1'], ages: ['3-4', '4-5', '5-6'], topics: ['colors', 'nature'], cat: 'colors' },

  // ==================== CORE TOPIC: NUMBERS (Chữ số & Đếm số) ====================
  { en: 'one', vi: 'Số một', ipa: '/wʌn/', pos: 'noun', units: ['B1_U1', 'B1_U5'], ages: ['3-4', '4-5', '5-6'], topics: ['numbers'], cat: 'numbers' },
  { en: 'two', vi: 'Số hai', ipa: '/tuː/', pos: 'noun', units: ['B1_U1', 'B1_U5'], ages: ['3-4', '4-5', '5-6'], topics: ['numbers'], cat: 'numbers' },
  { en: 'three', vi: 'Số ba', ipa: '/θriː/', pos: 'noun', units: ['B1_U1', 'B1_U5'], ages: ['3-4', '4-5', '5-6'], topics: ['numbers'], cat: 'numbers' },
  { en: 'four', vi: 'Số bốn', ipa: '/fɔːr/', pos: 'noun', units: ['B1_U1', 'B1_U5'], ages: ['3-4', '4-5', '5-6'], topics: ['numbers'], cat: 'numbers' },
  { en: 'five', vi: 'Số năm', ipa: '/faɪv/', pos: 'noun', units: ['B1_U1', 'B1_U5'], ages: ['3-4', '4-5', '5-6'], topics: ['numbers'], cat: 'numbers' },
  { en: 'six', vi: 'Số sáu', ipa: '/sɪks/', pos: 'noun', units: ['B1_U6', 'B2_U1'], ages: ['3-4', '4-5', '5-6'], topics: ['numbers'], cat: 'numbers' },
  { en: 'seven', vi: 'Số bảy', ipa: '/ˈsev.ən/', pos: 'noun', units: ['B1_U6', 'B2_U1'], ages: ['3-4', '4-5', '5-6'], topics: ['numbers'], cat: 'numbers' },
  { en: 'eight', vi: 'Số tám', ipa: '/eɪt/', pos: 'noun', units: ['B1_U6', 'B2_U1'], ages: ['3-4', '4-5', '5-6'], topics: ['numbers'], cat: 'numbers' },
  { en: 'nine', vi: 'Số chín', ipa: '/naɪn/', pos: 'noun', units: ['B1_U6', 'B2_U1'], ages: ['3-4', '4-5', '5-6'], topics: ['numbers'], cat: 'numbers' },
  { en: 'ten', vi: 'Số mười', ipa: '/ten/', pos: 'noun', units: ['B1_U6', 'B2_U1'], ages: ['3-4', '4-5', '5-6'], topics: ['numbers'], cat: 'numbers' },
  { en: 'eleven', vi: 'Số mười một', ipa: '/ɪˈlev.ən/', pos: 'noun', units: ['B2_U1', 'B3_U1'], ages: ['4-5', '5-6'], topics: ['numbers'], cat: 'numbers' },
  { en: 'twelve', vi: 'Số mười hai', ipa: '/twelv/', pos: 'noun', units: ['B2_U1', 'B3_U1'], ages: ['4-5', '5-6'], topics: ['numbers'], cat: 'numbers' },
  { en: 'twenty', vi: 'Số hai mươi', ipa: '/ˈtwen.ti/', pos: 'noun', units: ['B3_U1', 'B3_U9'], ages: ['5-6'], topics: ['numbers'], cat: 'numbers' },
  { en: 'count', vi: 'Đếm số', ipa: '/kaʊnt/', pos: 'verb', units: ['B1_U1', 'B2_U1'], ages: ['3-4', '4-5', '5-6'], topics: ['numbers'], cat: 'actions' }
];

// Deduplicate vocabulary while consolidating sourceUnits, ageGroups, and topics
const DEDUPLICATED_VOCABULARY = [];
const seenMap = new Map();

RAW_VOCABULARY.forEach(item => {
  const norm = item.en.toLowerCase().trim();
  if (seenMap.has(norm)) {
    const existing = seenMap.get(norm);
    item.units.forEach(u => {
      if (!existing.units.includes(u)) existing.units.push(u);
    });
    item.ages.forEach(a => {
      if (!existing.ages.includes(a)) existing.ages.push(a);
    });
    item.topics.forEach(t => {
      if (!existing.topics.includes(t)) existing.topics.push(t);
    });
  } else {
    const copy = {
      ...item,
      normalizedText: norm,
      mediaKey: `vocab_${norm.replace(/[^a-z0-9]/g, '_')}`,
      sourceType: 'OFFICIAL_CURRICULUM',
      status: 'ACTIVE'
    };
    seenMap.set(norm, copy);
    DEDUPLICATED_VOCABULARY.push(copy);
  }
});

module.exports = {
  VOCABULARY_DATA: DEDUPLICATED_VOCABULARY
};
